### ISSUE TITLE
[Export][2022-04-08] Empty files

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1012]
The original 2022-04-12 export had 8047 record files (+ role_data.json).

1970 of them are files containing only `{}`. Same problem as https://github.com/galterlibrary/digital-repository/issues/1000

Examples:

generic_file_zw12z533j.json 
generic_file_zw12z534t.json 
generic_file_zw12z5353.json
generic_file_0a3ac660-009c-4369-b80e-fb1ef0e004b9.json
generic_file_0c483j37r.json
generic_file_0c483j41b.json
generic_file_1ff46015-d6de-4141-811e-1be0a8977ee8.json

| Raw export | 8047 |
|---------------|----------|
| Non `{}` files | 6077|

**Comment by Meowcenary** [comment]
One of the issues here is that when the converter identifies a file as unexportable it will still write the file, but with empty json when it should just not export anything at all. Hopefully this is a simple fix.
