### ISSUE TITLE
[Export] 2022-04-26 Export feedback/issues

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1021]
Export summary:

communities: 36 / 36
drafts: 6101 / 6115
published records: 6101 / 6101

 Issue                                                                                                | # affected records                                      | Resolution        |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------- | ----------------- |
| Missing dates (https://github.com/galterlibrary/digital-repository/issues/953)                       | 4                                                       | [x]               |
| location.features.place as " " is invalid (generic_file_83503972-6778-411b-a4c0-4ebe79ddb42d.json)   | 1                                                       | [x] on the import |
| Invalid funding field (https://github.com/galterlibrary/digital-repository/issues/997)               | 6 (doesn't tally with previous analysis - I am investigating) | [ ]               |
| Invalid URL (generic_file_91aacfcd-67d3-4ac6-95ec-03e01d59af9e.json)                                 | 1                                                       | [ ]               |
| Invalid ARK  (generic_file_259f4ee2-dc18-442e-84fc-a269dd86206b.json)                                | 1                                                       | [ ]               |
| Duplicate subjects (generic_file_5d953a7d-d1c8-4b97-9a6d-241822f811ed.json)                          | 1                                                       | [x] on the import              |

Invalid URL in this case is a DOI interpreted as a URL.

```json
        {
          "identifier": "doi:10.18131/G3M91W", 
          "relation_type": {
            "id": "isRelatedTo"
          }, 
          "scheme": "url"
        }, 
```

Invalid ARK is a DOI interpreted as an ARK.

```json
        {
          "identifier": "10.1177/2374373521996982", 
          "scheme": "ark"
        }
```

Duplicate subjects is `{'subject': '12th General Hospital'}` appearing twice in the `subjects` field because of whitespace differences :sob: .

```
"subject": "12th General Hospital "
"subject": "12th General Hospital"
```

**Comment by Meowcenary** [comment]
Looping back around to this ticket:
- Ticket #997 is closed
- Invalid URL has been addressed as of the July 28th export
- Invalid ARK seems to be fixed as of the July 28th export (at least for the example here). The issues with the latest export blowing up are unrelated to the identifiers so we should be good here.

I'm going to move this to under review and wait until @fenekku signs off on this to close it out completely. It might make sense to wait until the next batch of fixes are in and we have a successful export.

**Comment by fenekku** [comment]
This can be closed. I know I solved the duplicate and whitespace issues on the import side. Anyway, we want to focus on the feedback from the latest export.
