### ISSUE TITLE
[Export] Original identifier(s)

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1023]
[Edited 2022-06-15]

DH records with "parsable" original identifiers should export those to Prism as [alternate identifiers](https://inveniordm.docs.cern.ch/reference/metadata/#alternate-identifiers-0-n).

Proposed approach

| DH field                                                          | Prism				 |
| ----------------------------------------------------------------- | ------------------ |
| `original_identifier` or find actual field mapping to original identifier | `identifiers` item |

For DH (https://digitalhub.northwestern.edu/files/bz60cw30w)

Original Identifier
    doi:46589
    (PMID) 11549777

Prism export:

```json
{
  "identifiers": [{
    "identifier": "11549777",
    "scheme": "pmid"
  }]
}
```

The original identifier DOI in that example is not a valid DOI (a valid doi is `<prefix>/<suffix>` with some rules), so it doesn't make sense to export. For DOIs, just checking against the shape in the export should be enough. On the import, we can use an already developed more sophisticated checker if need be.  

**Questions**

- What to do with original identifiers that don't map to a controlled scheme e.g. PNB-19-01 ?
- What to do with original identifiers created for GV Black e.g., m19091029 ? @gneidhardt  will see Katie [EDIT from [comment](https://github.com/galterlibrary/digital-repository/issues/1023#issuecomment-1156490325) ignore those as they are for the GV Black collections that should not be migrated]

**Comment by gneidhardt** [comment]
Unfortunately, this field is not included in the current file export from DigitalHub. @sharpattack, is this a field we can include on the next export? I can then see what all the examples are for the whole dataset. 

Looking at just the 50 files we sampled, these largely seem to be:

- PMID (pubmed ids) for some papers (example: (PMID) 34109874)
- article ids for the Pediatric Neurology Briefs (example: PNB-29-92), which will be numerous as there are 1000s of PNB articles
- original identifiers created for the GV Black collection (example: m19091029) - likely we'll need to consult with Katie on whether or not these need to stay in the record.

**Comment by Meowcenary** [comment]
@gneidhardt - I'm planning on getting to this ticket in the near future. Do you still want/need the export of the entires that don't conform to a standard schema? If so I'll enter a separate ticket for that.

**Comment by Meowcenary** [comment]
Pointing this relatively high since free text is usually difficult to work with. Probably going to involve some regex or something similar.

**Comment by Meowcenary** [comment]
@gneidhardt - I ended up just exporting a list of all the identifiers I found on production, but if you want to wait until I've had a chance to map some of these I can export another list later. 

The PMID fields are clearly labeled, some of the DOI fields are labeled in an obvious way, some other fields look like they might be DOIs but I'll need to check the format a bit closer (e.g 615.778-2), and finally many of the fields are very similar to file ids (e.g identifier is "PNB-29-53" and file id is "pnb-29-**7**-53"

[identifiers.csv](https://github.com/galterlibrary/digital-repository/files/9105541/identifiers.csv)

**Comment by Meowcenary** [comment]
The only two ISBN entries point to the same book on lookup because one is the 10 digit ISBN while the other is the newer 13 digit format. I'm just going to export the 13 digit ISBN unless someone objects.

https://www.isbn.org/about_isbn_standard#:~:text=For%20more%20than%20thirty%20years,converter%20found%20at%20this%20website.

**Comment by Meowcenary** [comment]
@gneidhardt no worries, hope it was fun and informative!

I consolidated the list of identifiers so that it was only what I couldn't identify and so that there were no duplicates. Please take a look and let me know what you want to do with these when you get a chance.



[consolidated_identifiers_list.csv](https://github.com/galterlibrary/digital-repository/files/9133082/consolidated_identifiers_list.csv)

**Comment by Meowcenary** [comment]
@gneidhardt no worries, hope it was fun and informative!

I consolidated the list of identifiers so that it was only what I couldn't identify and so that there were no duplicates. Please take a look and let me know what you want to do with these when you get a chance.



[consolidated_identifiers_list.csv](https://github.com/galterlibrary/digital-repository/files/9133082/consolidated_identifiers_list.csv)

**Comment by gneidhardt** [comment]
I have most answers, but a few I'll need to ask Katie (I've sent her an email, but she's out for two weeks unfortunately). Most of the ones at the beginning are identifiers for collections (and mostly GV Black), which we don't need. I do think we need to keep the Pediatric Neurology Briefs ids. Any that were DOIs I moved to the DOI section and deleted from original identifiers. Some of the 12th General Hospital ids at the end are marked as questions for Katie (as mentioned).

[consolidated_identifiers_list_gncomments.csv](https://github.com/galterlibrary/digital-repository/files/9135821/consolidated_identifiers_list_gncomments.csv)

**Comment by Meowcenary** [comment]
At 21/07/2022 DH migration meeting we decided to map the "PNB-..." with the schema "other". I'll add that, but we will still have to wait until Katie is back to get feedback on the 12 General Hospital records.

**Comment by gneidhardt** [comment]
Got some answers from Katie - tl;dr is that we don't need any of the 12th General hospital original identifiers. I will work on deleting these from DigitalHub. Longer answer for posterity is:

All of these records (https://digitalhub.northwestern.edu/catalog?utf8=%E2%9C%93&q=%22HSL.2016.15.0007%22) have the same original identifier (HSL.2016.15.0007). Do we need to keep it? 
Katie: This is the accession number for the Conner military insignia, and it’s in AS. NB: we were going to use HSL as a prefix in AS to easily distinguish our records. But AS only allowed numbers at the time, so we took the HSL out. Any leftover accession numbers with HSL should delete that prefix.

Similarly, these items all have unique identifiers (including one example of each) - do we need to keep the identifier?
https://digitalhub.northwestern.edu/catalog?utf8=%E2%9C%93&q=%22MM-MBS-COR-43-7124%22
https://digitalhub.northwestern.edu/catalog?utf8=%E2%9C%93&q=%229-Heskett%22
https://digitalhub.northwestern.edu/catalog?utf8=%E2%9C%93&q=%22223744%22
Katie: I see that the original identifier was taken from markings on the photo, which seems like the wrong field to record this info.

**Comment by Meowcenary** [comment]
Sorry it took me so long to loop around to this - I've been bouncing around a lot and got super disorganized. 

I'm going to update this branch and then verify that the logic is correct for what's in the latest CSV. If that's all set then I'll open a PR.
