### ISSUE TITLE
[Export] Switch publisher order in some cases

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1027]
*[Edsited 2022-06-29 with comment 1]*
Prism only accepts 1 publisher and the export selects the first publisher. In some cases, one of the other publishers "seems" a more appropriate choice to export. We need to determine if that's a correct switch and then do the switch.

**Case 1**

31 records with "Northwestern University" as potential publisher instead of DigitalHub. See https://digitalhub.northwestern.edu/catalog?_=1653602761911&f%5Bpublisher_sim%5D%5B%5D=Northwestern+University. 22 of which are parts of “A history of the Feinberg School of Medicine, written by Leslie B. Arey”. Should those be switched? See Katie or Karen. 
Note: Gretchen reinvestigated and only these records (all originating from Arey's book) should be considered. Still unsure whether we're considering this field to be digital publisher (in which case it would be DigitalHub) or original publisher (in which case it would be Northwestern University): 

- https://digitalhub.northwestern.edu/collections/areybook (22 records in this collection)
- https://digitalhub.northwestern.edu/files/406e5a26-e60d-4bac-9506-ddca25dbfa7c
- https://digitalhub.northwestern.edu/files/aa85a365-c493-42cf-922c-21ab24407a1e

**Case 2**

39 records with "Northwestern University, Medical School" as instead of DigitalHub. See https://digitalhub.northwestern.edu/catalog?_=1653602761908&f%5Bpublisher_sim%5D%5B%5D=Northwestern+University%2C+Medical+School. Including 10 that have NU Medical School as first publisher already. Should those be switched? See Katie or Karen. 

**Case 3**

Switch 3745 records to have "Pediatric Neurology Briefs Publishers" instead of DigitalHub as first publisher. See https://digitalhub.northwestern.edu/catalog?_=1653602761914&f%5Bpublisher_sim%5D%5B%5D=Pediatric+Neurology+Briefs+Publishers .

In all cases we assume that the change can be done on DH first or at export time.

**Status**

Gretchen will ask Katie and Karen and Ramune.

**Comment by gneidhardt** [comment]
Case 3 records should be switched (Pediatric Neurology Briefs Publishers should be first publisher). Cases 1 and 2 are still being investigated, and might have to be a case by case decision.

**Comment by Meowcenary** [comment]
@gneidhardt - finally getting back to this ticket. Have there been any updates on the first two cases or if we want to update the publisher order on DH itself?

I'm going to work on the third case now since it seems pretty simple, but I'll wait to merge anything until I hear back.

**Comment by gneidhardt** [comment]
This is a great question - I see @kglibrarian is already assigned, but I'd like her input here as I feel like we never figured out a clear decision to make in these cases, especially items like the Arey book that clearly have a publisher (Northwestern University), but were digitized specifically for Digital Hub.

Karen, you did send me a great email (on 6/22/22) but as I'm reading it I don't know that I see a conclusive decision that's proposed. As close as I can tell, would we decide that if something was officially published by a commercial entity (including Northwestern University Press) that should stay the Publisher, but if the item was non-commercially produced by a department and then digitized by the library, the publisher should stay DigitalHub?

**Comment by gneidhardt** [comment]
Just a quick clarifying note - based on feedback from Katie, I did change any publisher and/or creator instance of "Northwestern University, Medical School" to "Northwestern University Medical School" (no comma). This more correctly reflects the corporate org name of the institution at the time these items were created, so if you're doing a text string search, know that the comma is now missing from the publisher and creator fields.

**Comment by Meowcenary** [comment]
Oh wow, really glad I came back to read this. We'll need to update a data file to reflect this change, but it should not be a big change at all.

I'm going to mark it with the number on this ticket, but it seems like we're still waiting on feedback so I'll keep this ticket in blocked for now.

**Comment by Meowcenary** [comment]
Oh wow, really glad I came back to read this. We'll need to update a data file to reflect this change, but it should not be a big change at all.

I'm going to mark it with the number on this ticket, but it seems like we're still waiting on feedback so I'll keep this ticket in blocked for now.

**Comment by Meowcenary** [comment]
I decided that it made more sense to just put the small change for this ticket into a commit with general bug fixes so there wouldn't be a one line change. Leaving in blocked.

**Comment by gneidhardt** [comment]
Circling back to Case 3 here, as I noticed one in our metadata comparison (https://vtfsmghslrepo02.fsm.northwestern.edu/records/wdsnw-wc763):

**Case 3**

Switch 3745 records to have "Pediatric Neurology Briefs Publishers" instead of DigitalHub as first publisher. See https://digitalhub.northwestern.edu/catalog?_=1653602761914&f%5Bpublisher_sim%5D%5B%5D=Pediatric+Neurology+Briefs+Publishers .

**Comment by kglibrarian** [comment]
Can you let me know if there are problem records still (from my reading, everything looks fixed?)?  I am working on a document for our policy moving forward, but that shouldn't block this work from being done.

**Comment by gneidhardt** [comment]
Note to myself - align Case 1 and Case 2 so that "DigitalHub" is second publisher.

**Comment by Meowcenary** [comment]
@gneidhardt - thanks for the update, your help is really appreciated! I'll take a look at this today and let you know if anything comes up.

**Comment by Meowcenary** [comment]
For the third case I have something that I think will work, but I'm once again running into some annoying issues with querying the database that makes it difficult to see all the information I want.

Basically the plan is to check if the depositor had the user id "instituonal-pnb" (https://vtfsmghslrepo01.fsm.northwestern.edu/users/institutional-pnb) and if so search the publishers for "Pediatric Neurology Briefs Publishers" which if found is returned. There were a few records that I noticed combined Digitalhub and Galter Health Sciences Library which is a little concerning, but I think we should just include this in our next export and run a script or something similar to confirm we're exporting the right publisher this set of records.
