### ISSUE TITLE
[Export] Location

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1033]
*[Edited 2022-06-30 to take into account [comment 1](https://github.com/galterlibrary/digital-repository/issues/1033#issuecomment-1169107264)]*

In DH, geographic subject names are used to describe the locations the record is about. And location is used to describe the geographical location of presentation.

For the task about exporting geographic subject names go here: https://github.com/galterlibrary/digital-repository/issues/1032 .

This task is about exporting the location. 

| DH field                                                          | Prism				 |
| ----------------------------------------------------------------- | ------------------ |
| `location` (double-check) | presentation_location |

To export the original presentation location, add an entry to the `additional_descriptions` field in the export. The added additional_description item will look like:

```json
    {
      "description": "presentation_location: <value>",
      "type": {
        "id": "other"
      }
    },
```

Make sure locations are properly exported e.g. https://digitalhub.northwestern.edu/files/nv9352841 didn't have "Tucson, Arizona, United States" exported at all in the past.

This overrides how we were exporting locations before. We don't use the [InvenioRDM locations](https://inveniordm.docs.cern.ch/reference/metadata/#locations-0-n) field anymore for now, because it has the same meaning as the subjects field we will use.

**Comment by Meowcenary** [comment]
@gneidhardt - you rock! This is very, very helpful information and well written at that :D

I'm going to estimate this a little higher than some of the other tickets since there is a lot of information to process and past experiences with the location field have been very challenging. I will say this is a **5 point** ticket
