### ISSUE TITLE
[Export] Fix missing pediatric briefs community assignment 

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1037]
The 2022-04-26 export contains ~2000 records that should be marked as belonging to the `pediatric-neurology-briefs` community, but aren't currently. It looks like records from Pedriatic  Neurology briefs before Volume 15 are not assigned to that community in the export.

Example:

generic_file_pnb-10-9-70-b.json -- https://digitalhub.northwestern.edu/files/pnb-10-9-70-b 
has `"prism_community": ""` in the export but should have `"prism_community": "pediatric-neurology-briefs::Volume 10, Issue 09"`
(e.g. generic_file_pnb-27-2-4.json -- https://digitalhub.northwestern.edu/files/pnb-27-2-4 is good on the other hand with `"prism_community": "pediatric-neurology-briefs::Volume 27, Issue 02"`)

**Comment by kglibrarian** [comment]
Following this!

**Comment by Meowcenary** [comment]
Finally have a fix for this. There is a consistent naming scheme for these collections so we can use that to map to the prism community without having to enter each individual DH collection to prism community mapping.

**Comment by Meowcenary** [comment]
Found a bug for this :(

The top level collections for Pediatric Neurology Briefs use the string "pnb-<collection #>" (e.g pnb-1 , pnb-2) instead of "pnb-<collection #>-<brief #>" (e.g pnb-1-1, pnb-2-1). 

I think the below code is the best way to handle this. Going to make the change and add a new spec

```
[13] pry(main)> "pnb-1-1".split(/[^\d]/).reject(&:blank?)
=> ["1", "1"]
[14] pry(main)> vol, iss = "pnb-1-1".split(/[^\d]/).reject(&:blank?)
=> ["1", "1"]
[15] pry(main)> vol, iss = "pnb-1".split(/[^\d]/).reject(&:blank?)
=> ["1"]
```
