### ISSUE TITLE
Add netid of last editor to Subjects.csv

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#1048]

**Comment by sharpattack** [comment]
@gneidhardt for the last editor, I am able to easily extract `events` as follows:
``` ruby
 "User <a href=\"/users/qew348\">Q. Eileen Wafford</a> has deposited <a href=\"/files/pn89d6567\">fea_duggan_v27-2.pdf</a>; User <a href=\"/users/viq454\">Ilik, Violeta</a> has updated <a href=\"/files/pn89d6567\">2Assessing_the_impact_of_research.pptx</a>; User <a href=\"/users/keg827\">Gutzman, Karen E</a> has deposited <a href=\"/files/pn89d6567\">2Assessing_the_impact_of_research.pptx</a>" 
```

This includes ALL events on a record. Would you just want the last performed event? So in the above example, it would just be `User <a href=\"/users/qew348\">Q. Eileen Wafford</a> has deposited <a href=\"/files/pn89d6567\">fea_duggan_v27-2.pdf</a>"`, and this is what would display in the csv file.

**Comment by gneidhardt** [comment]
Yes, preferably just the last performed event. Thank you so much - this is very exciting!
