### ISSUE TITLE
[Export] Make Northwestern University (Evanston Ill.). Medical Alumni Association an org creatibutor

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1055]
The following gets generated for a couple records:

```
"person_or_org": {
  "family_name": "Northwestern University (Evanston",
  "given_name": "Ill.). Medical Alumni Association",
  "type": "personal"
},
```

The issue behind this may affect other records and have a more general solution.

**Comment by Meowcenary** [comment]
There's some shaky logic for determining an org and a personal record within `InvenioRdmRecordConverter#build_creator_contributor_json` which is causing this. There's a function `organization?` that can probably be used to fix this.
