### ISSUE TITLE
[Export] Empty funding information for record 78254bed-92a7-4708-bcff-16383bab9ce3

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1056]
The record https://digitalhub.northwestern.edu/files/78254bed-92a7-4708-bcff-16383bab9ce3 is exported with the following funding information:

```json
      "funding": [
        {
          "award": {
            "identifier": "", 
            "number": "", 
            "scheme": "", 
            "title": ""
          }, 
          "funder": {
            "identifier": "", 
            "name": "", 
            "scheme": "ror"
          }
        }
      ], 
```

which can't be imported. If this record was supposed to have funding information, we should provide it. Otherwise we should correct this export.

It doesn't have an entry in the metadata_addons.csv of galter-ir-importer either.

**Comment by gneidhardt** [comment]
From the file itself "Support: No financial support, no review funder or sponsor." - this funding information should be deleted. I tried to do an add and delete to the field in DigitalHub, but the field was already empty so I don't know where that scheme: "ror" came from (especially since DH doesn't capture that information).

**Comment by fenekku** [comment]
Thanks @gneidhardt . It must be on the export side then @Meowcenary

**Comment by Meowcenary** [comment]
I'm not sure why, but at some point I decided to do this:

```
BLANK_FUNDER_SOURCE = {funder: {name: "", identifier: "", scheme: "ror"}, award: {title: "", number: "", identifier: "", scheme: ""}}
```

Still not sure why the scheme is "ror" though

**Comment by gneidhardt** [comment]
"ror" is the scheme we're using as a controlled vocabulary for funding names (ror.org) - does this help, or is this a different question? I might be misunderstanding...

**Comment by Meowcenary** [comment]
Oh I was just commenting to track what I had found so far. Most of the tickets do not have too many people on them so you can use comments as notes without notifying a lot of people. I should probably not do that for these tickets since a lot of people are on them ha
