### ISSUE TITLE
Related files not linked in Prism (possibly expected)

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1085]
I haven't seen this come up before, so it might be a non-issue.

https://digitalhub.northwestern.edu/files/a8ea36c6-a95f-4de2-ab7c-e5e15df46484
https://vtfsmghslrepo02.fsm.northwestern.edu/records/myw89-yf437

In these two, there are system-generated "related files" in the File Details section of DH, but these aren't present in Prism. I'm not totally sure what generates these in DH (the collection it's a part of)? @kglibrarian do you know? This file is still linked with these files (and others) through the 12th gen hospital community, so I'm not sure how urgent this issue is. Would appreciate insight from others if they have it.

**Comment by sharpattack** [comment]
@gneidhardt Related Files in DigitalHub are created when a user selects multiple files to upload. It should be read as "other files uploaded at the same time as this record". We will need a place to store it if we keep it. Maybe in Related Works?

**Comment by gneidhardt** [comment]
I don't personally have any super strong feelings about how important this information is to retain - do others have thoughts? I like the idea of it going with Related Works.

**Comment by sharpattack** [comment]
Ah ha, it must be for site admins then. Logged in with our test student account, gso1135, I still don't see it.

**Comment by gneidhardt** [comment]
It looks like this, but I'm ok with "nothing to do here" since as you point out it's not publicly visible data.

![image](https://user-images.githubusercontent.com/84924248/189960154-82f5ff9f-37fe-4dc5-a162-f6cb09a2dfee.png)

**Comment by kglibrarian** [comment]
I am ok with doing nothing too. We often upload batches of files, not expecting them to be related. I didn't know that was a feature of DigitalHub! Good to know now that we aren't using it anymore.

**Comment by fenekku** [comment]
Closing this task then. Thanks,
