### ISSUE TITLE
Map LCSH Resumes (Employment) in DH to Résumés (Employment) 

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1087]
> Resumes (Employment) is still an issue (see https://vtfsmghslrepo02.fsm.northwestern.edu/records/myw89-yf437 and https://digitalhub.northwestern.edu/files/a8ea36c6-a95f-4de2-ab7c-e5e15df46484). I'm guessing LCSH Resumes (Employment) didn't migrate from DH because it's missing its diacritics in DH (they don't display). Would the solution here be to add this to items that should have this in Prism as the actual LCSH text ("Résumés (Employment)")? This would affect 57 records, which is possible manually, but if there is a way to do it automatically that would be great. 

> Here's the full list for my reference: https://digitalhub.northwestern.edu/catalog?f%5Btags_sim%5D%5B%5D=Resumes+%28Employment%29&q=%22resumes+%28employment%29%22

_Originally posted by @gneidhardt in https://github.com/galterlibrary/digital-repository/issues/1036#issuecomment-1244482628_

This should just be a matter of changing the memoized mapping @meowcenary right? (i.e. no work for Gretchen)

**Comment by Meowcenary** [comment]
Finally getting around to this.

> This should just be a matter of changing the memoized mapping @Meowcenary right? (i.e. no work for Gretchen)

Yes, I think we just need to update that character in the memoized file and we should be good to go. These diacritics (I didn't know that's what they were called, fancy!) are really causing a lot of problems -_-
