### ISSUE TITLE
[Export] PDF page count for some records is off

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1088]
This is an error both in DH and Prism, so possibly a bug with the file. PDF file page count in both DH and Prism is "0 pages", but this PDF has 44 pages.

https://vtfsmghslrepo02.fsm.northwestern.edu/records/9zh4q-y4k87
https://digitalhub.northwestern.edu/files/9cd9e3df-458c-4a2c-9e42-1dcdc95e7adf

Screenshot of DH (it's in admin data):
![image](https://user-images.githubusercontent.com/84924248/190189182-6fded365-cf79-40e8-9b10-c3aa9913472b.png)

**Comment by gneidhardt** [comment]
Note: also happening with https://vtfsmghslrepo02.fsm.northwestern.edu/records/653g4-8m023. Is this because files are restricted?

**Comment by fenekku** [comment]
This is an export issue. Prism shows the page count that was extracted on DH. 

Is it possible to change that page count on the DH UI?

If not we need to fix this at export time or as a touch up in the migration addons file?

Related sidenote: given that not all columns in the migration addons file are relevant to all entries, would it make it easier for you @gneidhardt if that file were a json file like:

```json
{
  <dh_id>: {
    <field to change>: <new value>,
    <another field to change>: <new value>
  }
}
```
?

**Comment by fenekku** [comment]
Transferred from https://github.com/galterlibrary/digital-repository/issues/1104 by @gneidhardt :

page count issue: problem originates in DH, but system generated metadata gives two page counts (73, 116) - replicated in Prism, but should just be 116 pages

https://digitalhub.northwestern.edu/files/3105875f-61e1-412c-9b1c-c8a33b37ff35	https://vtfsmghslrepo02.fsm.northwestern.edu/records/q7kyq-9hg73

**Comment by Meowcenary** [comment]
This seems like a situation where we will just need to specify the pages for these instances. I'll make changes to the export and add them with some bug fixes.

**Comment by sharpattack** [comment]
@gneidhardt Do we have a page count for https://vtfsmghslrepo02.fsm.northwestern.edu/records/653g4-8m023 ? I think it's this record on digitalhub https://digitalhub.northwestern.edu/files/d2b48b7b-5322-4b1b-ae01-106d73b35263

**Comment by gneidhardt** [comment]
This should be 32 pages - the PDF preview has correctly listed the page count for all the examples I've seen. We noticed that all of the NUCATS Grant Repository items we checked had page counts of 0 - wasn't sure if this was because they're restricted in DH? Not sure why that would affect page count, but that was the only common variable I could think of, unless they're created in some kind of unique way that means page count isn't captured initially.

**Comment by sharpattack** [comment]
Oh wow, ALL of the NUCATS Grants Collection? 🤔 Makes me wonder what the user's workflow was. Or what the original uploaded file looks like, and is causing 0 page counts.

**Comment by gneidhardt** [comment]
I want to caution I haven't looked at all the the NUCATS grant collection items individually in Prism, but this happened in all 5-6 examples that we sampled for in this most recent metadata review, so I think it might be a collection-level issue.
