### ISSUE TITLE
[OPS] Manually change DH related urls to DOI or Prism related urls

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1089]
Might be a non-issue, but just in case it isn't. For https://vtfsmghslrepo02.fsm.northwestern.edu/records/r0gyq-x8005 related URLs are correct, but they point towards DH URLs - will these be changed or redirected to Prism URLs? This will be an issue for lots of items that point towards related IR items with the "related urls".

I do see we have some notes about this from last time, but I'm not sure on the implementation of changing DH URLs to DOI URLs - are we doing this work manually in DH, or is this automated someway? I wasn't sure if the Prism DOI URLs were live yet.

NOTES FROM MAY METADATA COMPARISON
(Column S) Related URL – some of these didn’t map to Prism, and there was at least one instance where Related URLs were DigitalHub URLs – do we need to search and replace these or will they redirect? 

Use DOI URL, which should remain stable, but not available immediately (so will need to wait to add these) 

Only 17 – replaced when links to an Open DH DOI 

Exceptions – doi.org/10.18131/g3-1b91-6b09 ; doi.org/10.18131/g3-p7k2-2t51 ; and doi.org/10.18131/g3-havk-rp07 all link to a DH link, but it’s a collection, so no DOI available (https://digitalhub.northwestern.edu/collections/07b25bee-4a47-466a-b9b8-70d7a392fab0) 

Exceptions, which are all registered/Northwestern Only files without public DOI URLs - doi:10.18131/g3-3h47-p563 ; doi:10.18131/g3-wxxg-dt11 ; doi:10.18131/g3-mxkr-0r60 ; doi:10.18131/g3-nqka-zn57 ; doi:10.18131/g3-2rgc-cs87 ; doi:10.18131/g3-17xr-5h35 ; doi:10.18131/g3-d94s-8553 ; doi:10.18131/g3-aw1c-6y08

**Comment by fenekku** [comment]
It's not an immediate issue, but it is something that will need to be dealt with after going to production. There is a ticket on Prism for this: https://github.com/galterlibrary/digitalhub-2/issues/136 . Since DH will continue running in read-only for a while this should not be problematic.

We can take some time then to think about the strategy for those.

**Comment by sharpattack** [comment]
CSV list of records with Related URLs with `digitalhub.northwestern.edu addresses`: https://nuwildcat.sharepoint.com/:x:/r/teams/gl_FSM_GalterStaff/Shared%20Documents/Digital%20Initiatives%20Working%20Group/DigitalHub_Migration/related_url_to_doi.csv?d=wb22c362fc9b348e29c7bfc8b20bd680b&csf=1&web=1&e=nNmUbJ

**Comment by fenekku** [comment]
This is affected by work done on https://github.com/galterlibrary/digitalhub-2/issues/136 , so I will take it over.

**Comment by fenekku** [comment]
Email sent to @gneidhardt about this.

File with mapping to use by staff who will perform manual update:

[related_urls_to_update.csv](https://github.com/galterlibrary/digital-repository/files/11225843/related_urls_to_update.csv)

**Comment by gneidhardt** [comment]
I made this csv a shared file in the Galter-Staff/Digital Systems/Prism folder: https://nuwildcat.sharepoint.com/:x:/t/gl_FSM_GalterStaff/EQnsxqI4zpVGmqB3Z4UcqS4B_upNnuTE9yWv1KJlpK-y0Q?e=kXUk8T

I claimed the first 40 records, but can keep going after that if needed. If others want to claim any to manually change, I added a column. For claimed records, I put my initials and highlighted – I’ll add the date and unhighlight once I’ve made the changes in Prism.

**Comment by gneidhardt** [comment]
Question for @fenekku and @kglibrarian as I'm making my changes - for the links that are now DOIs, do we want to enter these as related URLs, or as DOIs? I was just kind of replacing them as URLs on autopilot, but we can enter them now as DOIs, and they are still hyperlinked.

Here they are as URLs:
![image](https://user-images.githubusercontent.com/84924248/232514377-d4cef055-cdaf-4650-ad8b-879ff68013be.png)
(see it live - https://doi.org/10.18131/g3-kw4a-xj25)

And here they are as DOIs:
![image](https://user-images.githubusercontent.com/84924248/232514967-08041615-1e8a-40dd-a533-b4da7e838ab4.png)
(see it live - https://doi.org/10.18131/g3-zdd1-ff75)

**Comment by fenekku** [comment]
From my end either is fine. DOI is probably more specific, but the URL option makes the link more visible (it's clearer in some sense) I think :shrug: .

Karen or other metadata experts may have a better insight on this.

**Comment by kglibrarian** [comment]
I agree with Guillaume's comment. I think maybe we should use DOI since it's the most specific entity.

**Comment by gneidhardt** [comment]
That is also where I was leaning, so that sounds good! I'll change the ones I've already done and make a note. Also if you all want me to take the rest I'm happy to do it - it goes very quickly.

**Comment by kglibrarian** [comment]
Oh, good! I am glad we had a similar view. Thank you for doing this. Yes, if you can take the rest, that would be very much appreciated.

**Comment by gneidhardt** [comment]
These have all been updated
