### ISSUE TITLE
DOI prefix different in DH vs Prism

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1092]
I thought we had documentation about this, but I couldn't find it in my email or on OneDrive, or in the /digital-repository existing issues. Just to confirm though, DOIs in Prism all start with 10.24418/ and the corresponding DOIs in Digital Hub largely start with 10.18131/. The suffixes in each system are the same for mapped items, but I want to confirm that it's ok that the prefixes are different. 

Here are some examples:

- https://digitalhub.northwestern.edu/files/dbaffe67-13f5-469b-b7d8-6f427c6f2a99 and https://vtfsmghslrepo02.fsm.northwestern.edu/records/x3xk2-mqb67
- https://digitalhub.northwestern.edu/files/6t053f96k and https://vtfsmghslrepo02.fsm.northwestern.edu/records/7gjk0-pn594
- https://digitalhub.northwestern.edu/files/f64e0aad-7071-407f-8d64-7dfbb6114090 and https://vtfsmghslrepo02.fsm.northwestern.edu/records/qn566-wjn69

**Comment by fenekku** [comment]
Here is a recap of the DOI situation:

In DH, we have records with the 10.18131 prefix and various other prefixes from other institutions. 10.18131 is our prefix. In Prism staging, those DOIs with 10.18131 have been converted to have a 10.24418 prefix. The 10.24418 prefix is our test DOI prefix. This way we were able to reproduce the full DOI url resolution migration in staging. You can visit our datacite test fabrica account and see the records registered there.

In Prism production, the 10.18131 prefix will be kept i.e. we will actually be changing the URL resolution of the real DOIs. So records under our DOI control in production Prism will have the same DOI prefix as in production DH.

**Comment by gneidhardt** [comment]
Thank you! This is very helpful :)

**Comment by kglibrarian** [comment]
Thanks - seeing this now!
