### ISSUE TITLE
Create Calantone et al 2022 Commun Biol Source Data + 1952 Oral history community entry in mapping file

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1093]
Unsure if related to #1012 or not, but some items in DH collections are not displaying as being part of a community in Prism on the front end, and when there is what seems to be a community id in the JSON, it doesn't lead anywhere. Example:

- https://digitalhub.northwestern.edu/files/3cecfa2d-9818-4ebe-80fc-c3b2ca3a146a, part of https://digitalhub.northwestern.edu/collections/5f1b1739-512f-4015-98bc-22f37f42af7b community
- https://vtfsmghslrepo02.fsm.northwestern.edu/records/kg98b-b6k43, no public community, and this is under parent in json:
 "parent": {
    "access": {
      "links": [],
      "owned_by": [
        {
          "user": 305
        }
      ]
    },
    "communities": {},
    "id": "0bxz4-1yy74"

**Comment by fenekku** [comment]
"Calantone et al 2022 Commun Biol Source Data" is not a community in our export lists yet :

- https://github.com/galterlibrary/digital-repository/blob/master/dh_collections_prism_collection_community.json
- https://github.com/galterlibrary/galter-ir-importer/blob/master/data/communities.json

Made a ticket in galter-ir-importer for it: https://github.com/galterlibrary/galter-ir-importer/issues/98 . This issue in digital-repository should be kept so the change in digital-repository can then be made too.

**Comment by gneidhardt** [comment]
Note: this issue is also present in these files:
https://digitalhub.northwestern.edu/files/58fd018e-4409-4c1f-b7cf-042457401caf	https://vtfsmghslrepo02.fsm.northwestern.edu/records/9d5ad-cdt76

Since this has happened in at least two cases, I'm worried there are more out there, but unsure how to assess without looking at each item manually. Any thoughts?

**Comment by fenekku** [comment]
@kglibrarian @klattal Should a community be created for "Class of 1952 Oral History Collection". There isn't a tab for it in the collection spreadsheet (https://nuwildcat.sharepoint.com/:x:/r/teams/gl_FSM_GalterStaff/_layouts/15/Doc.aspx?action=default&file=2022_02-18%20DigitalHub%20Migration%20Plan%20for%20Collections.xlsx&mobileredirect=true&sourcedoc=%7B259E0FE1-B7FD-42DF-8D07-1AAE9AAAD152%7D&cid=e8516d54-3ab8-4326-96cc-dcd4171c8163).

If yes, then I've created this ticket: https://github.com/galterlibrary/galter-ir-importer/issues/101, but metadata should be provided by expert.

**Comment by klattal** [comment]
@fenekku no, this should be part of the "AV Archives" community
