### ISSUE TITLE
Name Subject "Northwestern University (Evanston, Ill.). Medical School" mapped incorrectly

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1094]
In many DH items, the name subject "Northwestern University (Evanston, Ill.). Medical School" is incorrectly changed to "Northwestern University (Evanston, Ill.). Department of Rehabilitation Medicine" in front and back end of Prism.

Examples:
https://digitalhub.northwestern.edu/files/9b710ed2-264c-4688-8404-3848d770314d	https://vtfsmghslrepo02.fsm.northwestern.edu/records/f218a-e1470

https://digitalhub.northwestern.edu/files/2575a0d7-4c87-4273-b80a-df27cf9fff6f	https://vtfsmghslrepo02.fsm.northwestern.edu/records/vj6jy-0dj13

https://digitalhub.northwestern.edu/files/506cbdca-cd9d-43fd-9be7-4b1b912782e5	https://vtfsmghslrepo02.fsm.northwestern.edu/records/aqjeb-56x38

**Comment by Meowcenary** [comment]
Here's the pid we want: https://id.loc.gov/authorities/names/n84204964.html (thanks @gneidhardt for finding this!)

**Comment by Meowcenary** [comment]
There are some other subject names that are very similar to this so I'm going to try and find pids for those too.

- Northwestern University (Evanston, Ill.). Medical School. Library
- Northwestern University (    Evanston, Ill.). Medical School--Buildings
- Northwestern University (Evanston, Ill.). Medical School--Alumni and alumnae
- Northwestern University (    Evanston, Ill.). Medical School--Faculty

**Comment by gneidhardt** [comment]
Just a note - if there's a space between ( and Evanston, that shouldn't be there. I can search for that and fix them in DH if needed, but let me know - I don't want to create discrepancies between DH and your memoization files if that will get confusing.

Also some notes:

- Northwestern University (Evanston, Ill.). Medical School. Library (no2011013629)
- Northwestern University ( Evanston, Ill.). Medical School--Buildings (not an official heading as one full string - in LOC headings "--Buildings" is an allowable subheading to put with institutions - so I guess this might be n84204964sh85017769, which is the Medical School pid and Buildings pid put together?)
- Northwestern University (Evanston, Ill.). Medical School--Alumni and alumnae (also not an official full heading - possibly n84204964sh85004049)
- Northwestern University ( Evanston, Ill.). Medical School--Faculty (also not an official full heading - possibly n84204964sh85046860 - additionally this is wrong - it should be "Northwestern University (Evanston, Ill.). Medical School--Faculty (Education)"

**Comment by Meowcenary** [comment]
> Just a note - if there's a space between ( and Evanston, that shouldn't be there. I can search for that and fix them in DH if needed, but let me know - I don't want to create discrepancies between DH and your memoization files if that will get confusing.

Thanks for offering to edit, but I think at this point it's just easier to let the memoized mapping handle it.

Thanks for the help looking up the other pids! I'll add them to with the other changes for this ticket and we can always revert the mappings later if we need to.
