### ISSUE TITLE
Responsive design for files box is not working

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1095]
I think this has come up in our meetings, but I didn't see an issue about it so thought I'd post here. Feel free to delete if it is elsewhere.

When an item in Prism has a long file title, and the browser window is smaller, the file box goes "under" the sidebar.

See this item: https://vtfsmghslrepo02.fsm.northwestern.edu/records/dm2wd-6s623

Screenshot:
![image](https://user-images.githubusercontent.com/84924248/191543668-51d63a6f-468a-4a17-8908-2914b9cc9b5d.png)

**Comment by sharpattack** [comment]
@gneidhardt Yep! I reported it here, too https://github.com/galterlibrary/digitalhub-2/issues/272 And is also reported upstream. I just did not find an example on Prism. 

Marking as duplicate.
