### ISSUE TITLE
Checking - item added to Community in Prism, but not part of any collection in DH

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1103]
Confirming this is correct (seems fine topically), but odd behavior for an item with no collection in DH to get added to a community in Prism:
https://digitalhub.northwestern.edu/files/506cbdca-cd9d-43fd-9be7-4b1b912782e5	https://vtfsmghslrepo02.fsm.northwestern.edu/records/aqjeb-56x38

**Comment by fenekku** [comment]
Yes that's fine. This was on purpose (https://github.com/galterlibrary/digital-repository/blob/master/dh_collections_prism_collection_community.json#L296). Thanks for checking!
