### ISSUE TITLE
Error in page count - originates in DH, replicated in Prism

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1104]
page count issue: problem originates in DH, but system generated metadata gives two page counts (73, 116) - replicated in Prism, but should just be 116 pages

https://digitalhub.northwestern.edu/files/3105875f-61e1-412c-9b1c-c8a33b37ff35	https://vtfsmghslrepo02.fsm.northwestern.edu/records/q7kyq-9hg73

**Comment by fenekku** [comment]
Moving this into https://github.com/galterlibrary/digital-repository/issues/1088
