### ISSUE TITLE
Ignore Records With "- Combined" In Title from Export

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#1113]
Don't export records that end with "- Combined".

**Comment by Meowcenary** [comment]
This directly ties into some work I'm doing so it should be easy to tackle this.

**Comment by fenekku** [comment]
Marking as blocked until hear back from Karen and Gretchen

**Comment by sharpattack** [comment]
Confirmed from Gretchen and Karen, unblocking.

**Comment by Meowcenary** [comment]
Okay, I'll knock this out quick and then we can plan on releasing (again) later today
