### ISSUE TITLE
[Develop] Disable File Editing For All Except Specific Users

### ISSUE THREAD

**Issue by Meowcenary** [galterlibrary/digital-repository#1117]
This is probably going to mean removing CanCan roles from users so that they have very limited permissions.

Test this on staging first and then check with @kglibrarian for what communications need to go out alerting that this change will take effect and for when the change should take effect.

**Comment by Meowcenary** [comment]
Whoops, this is _not_ blocked. I remember looking into this previously and have some challenges, but I can revisit for November sprint.

**Comment by Meowcenary** [comment]
Blocking this. After discussion in the latest migration meeting it seems like the best option is to try to remove the edit buttons from all views (similar to disabling the filed upload). 

After the date we disable editing and uploading files we will attempt to make any final changes through the database directly. If it turns out there are too many files for this to be reasonable, which is unlikely, we'll unblock this and continue work on it.

**Comment by fenekku** [comment]
From 2023-03-30 migration meeting:

we will need a way to let Gretchen edit while others can't.

**Comment by Meowcenary** [comment]
I'm changing this to "easy" effort now that we better understand how to approach this. Also, unblocking.
