### ISSUE TITLE
[Export] Return [] for sizes as last alternative

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1122]
The export (2022-10-20) exports `"sizes": null` when https://github.com/galterlibrary/digital-repository/blob/master/app/models/invenio_rdm_record_converter.rb#L615 doesn't match any of the conditional branches. InvenioRDM doesn't accept `null`, it only accepts `[]`. Just a matter of returning `[]` in an else branch.

I will make a temporary fix for the export data, but it should be fixed in the export phase for next imports.

**Comment by Meowcenary** [comment]
I misspoke at the migration meeting earlier. This is actually being exported for some records. Doesn't change the OP at all, but I think I should shame myself a bit for that :P
