### ISSUE TITLE
[Export] strip leading/ending whitespace from DOI identifier

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1124]
The export generated:

```json
"pids": {
      "doi": {
        "client": "digitalhub",
        "identifier": " 10.1007/s11899-017-0400-3",
        "provider": "datacite"
      }
    },
```

but should generate (notice the removed whitespace in front of the identifier):

```json
"pids": {
      "doi": {
        "client": "digitalhub",
        "identifier": "10.1007/s11899-017-0400-3",
        "provider": "datacite"
      }
    },
```

This only affected 1 record in the 2022-10-20 export though.

**Comment by Meowcenary** [comment]
I kind of glossed over this previously, but it's a really simple fix.

Ruby's strip method will handle this for us so I just tacked it on where the DOI was being formatted into JSON

Here are some examples of it at work
```
" 12345 ".strip
 => "12345"
" 10.1007/s11899-017-0400-3".strip
 => "10.1007/s11899-017-0400-3"
" 10.1007/s11899-017-0400-3 ".strip
 => "10.1007/s11899-017-0400-3
```
