### ISSUE TITLE
[Export] Records Failing to Map to Prism Community

### ISSUE THREAD

**Issue by Meowcenary** [galterlibrary/digital-repository#1127]
Currently the below record ids from the collections Galter Health Sciences Library Collections are not mapping to any Prism communities

**Galter Health Sciences Library Collections**
- `44b38071-0e12-4ae2-8050-dff27d135e52`
- `4857d647-b625-471b-aedd-760b297e3a00`
- `985d886e-bf2c-4e1c-be30-a67fbaec5ba7`
- `d1dc70b2-e059-4277-91ea-8f4ae49b37a2`
- `6210685a-ec42-4e5a-9554-33ece2aa2ef2`
- `8e0cd33d-080e-4a2d-9ee1-c2ed2821d40a`
- `c67fa295-5187-4180-9c99-19c9eb025a27`
- `ff39c06e-c310-422f-ba0c-abdd4e85484d`

**Comment by Meowcenary** [comment]
Go through latest export, search for export file tied to each generic file's id, check collection field and if it's empty check record converter for errors.

**Comment by fenekku** [comment]
The `"prism_community"` field for most of those records in the export is empty `""`. All those records were made by Tony Olson.

**Comment by kglibrarian** [comment]
So, I think that means we need to add the json below to this file: https://github.com/galterlibrary/digital-repository/blob/master/dh_collections_prism_collection_community.json

"3e59c5b9-bbbf-4f49-946f-e08ef9b10d9f": {
   "collection_id": "Library of Congress Subject Headings Authority Records with Medical Subject Headings mapping data",
   "community_id":  "galter-health-sciences-library-and-learning-center"
},
"4b7f6a77-9cf4-4deb-b9aa-f3f49391bcc8": {
   "collection_id": "Medical Subject Headings Authority Records with Library of Congress Subject Headings mapping data",
   "community_id": "galter-health-sciences-library-and-learning-center"
}

Which will add 8 files total from these two collections in DigitalHub: 
- https://digitalhub.northwestern.edu/collections/3e59c5b9-bbbf-4f49-946f-e08ef9b10d9f
- https://digitalhub.northwestern.edu/collections/4b7f6a77-9cf4-4deb-b9aa-f3f49391bcc8

**Comment by kglibrarian** [comment]
Not sure if my comment was clear - I don't actually know if that's the correct thing to do....it seems like it is?
