### ISSUE TITLE
[Export] Item in community in DH but not in Prism

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1137]
> >5. Item is in a community in DH, but not in Prism (this might be intentional, so I’m also tagging
@kglibrarian to comment): https://digitalhub.northwestern.edu/files/1f4e2f87-12fa-4b2b-a0d3-70e162806ba8 and https://vtfsmghslrepo02.fsm.northwestern.edu/records/fj6p2-vbp47

To check if this is right or not 

- [ ] according to our current rules
- [ ] according to Karen's export rules

**Comment by Meowcenary** [comment]
> It appears that the collection "Library history timeline images" does NOT appear on the Collections page in DigitalHub anywhere. Could this be an institutional collection or a researcher's collection that didn't get added to the Collections page for some reason?

I'll start looking into this. 

> I can check with Katie on where she wants this collection to live.

That would be helpful!

> Could there be more collections like this that aren't appearing on the DigitalHub Collections interface?

I'm hoping that once we have an answer to the first question we'll know how to identify these types of collections and then we can write up a script or query to find any others.

**Comment by Meowcenary** [comment]
It looks like this collection is private which is why it's not showing up on the collections index. Once @kglibrarian has had a chance to ask Katie about which community this should map to we can update `dh_collections_prism_collection_community.json` to include that mapping and I think that will resolve the issue. Moving to "blocked" until we hear back from Katie.

**Comment by kglibrarian** [comment]
I thought that private collections would show up on the collections index page if logged in as a system administrator (?). So there very well could be additional collections that I don't know of. I don't know how to find them if I can't see them as a system admin on the interface. Katie would like the files to continue to be private but added to the new "History of Feinberg School of Medicine" collection in Prism.

**Comment by Meowcenary** [comment]
> I thought that private collections would show up on the collections index page if logged in as a system administrator (?). 

From what I found the only things listed here: https://digitalhub.northwestern.edu/collections are open access. I'll double check tomorrow.

> I don't know how to find them if I can't see them as a system admin on the interface

I can throw a script together to find private collections and list out the IDs if that would be helpful?

> Katie would like the files to continue to be private but added to the new "History of Feinberg School of Medicine" collection in Prism.

Okay, I'll go ahead and add that mapping tomorrow. Moving this to "In Progress"

**Comment by kglibrarian** [comment]
I think my litmus test is the "NUCATS Center for Education and Career Development"  - which is a private collection that I can see when logged in as System Admin and not see when I'm not logged in. Regardless, perhaps not all collections behave that way. Yes, please let me know the IDs of private collections. Thank you!!

**Comment by Meowcenary** [comment]
> I think my litmus test is the "NUCATS Center for Education and Career Development" - which is a private collection that I can see when logged in as System Admin and not see when I'm not logged in. Regardless, perhaps not all collections behave that way. 

While logged in I'm not seeing that listed under the collections index here: https://digitalhub.northwestern.edu/collections , is there somewhere else you're finding it or is it on that page? The only NUCATS collection I'm seeing is "[NUCATS Series on Developing and Enhancing Mentoring Relationships](https://digitalhub.northwestern.edu/collections/98aba013-3005-4cbe-9fb0-e21960a8e274)". I've attached a screenshot of the collections page that I'm seeing.

<img width="1179" alt="Screen Shot 2022-11-16 at 9 22 04 AM" src="https://user-images.githubusercontent.com/13144027/202221089-ab30de0e-2a45-4107-8c4e-a39132827666.png">

> Yes, please let me know the IDs of private collections. Thank you!!

I'll go ahead and get the list of private collections when I get a chance.

**Comment by kglibrarian** [comment]
Below is what I see, which does include the NUCATS collection I was referring too. I assumed it was because System Admins could see private collections. But since I don't really have much documentation about DigitalHub, maybe that's not the case. 

![image](https://user-images.githubusercontent.com/15878040/202222692-a1a2941c-bbe8-4da9-a411-caf64eacd330.png)

**Comment by Meowcenary** [comment]
From the database it seems like there are many different types of admin and I only have two of these roles while you have seven. I think this explains why you're seeing more than myself on that page. For what it's worth I can still search the catalog for "NUCATS Center for Education and Career Development" and then view and edit it. 

Here is the results from the database with our respective roles:
```
2.3.7 :011 > User.find_by(email: "eric.newman@northwestern.edu").roles.map{ |r| r.name }
 => ["admin", "Galter-Health-Science-Library-Feinberg-School-of-Medicine"]
2.3.7 :012 > User.find_by(email: "karen.gutzman@northwestern.edu").roles.map{ |r| r.name }
 => ["admin", "NUCATS-Grants-Repository-System-Admin", "Biostatistics-Collaboration-Center-Lectur-Admin", "Center-for-Data-Science-and-Informatics-System-Admin", "SiS-Admin", "Communication-Bridge-System-Admin", "Covid-System-Admin"]
```

**Comment by Meowcenary** [comment]
@kglibrarian will be making this edit. Once the PR is up we can close this out. Reassigning to her.

**Comment by Meowcenary** [comment]
Follow up with @kglibrarian to see if there is a PR up with the changes necessary.

**Comment by kglibrarian** [comment]
Yes - see that the collection "Library History Timeline Images" is in this issue: 

- dh_collections_prism_collection_community.json in the digital-repository github repo to include the 4 new collections (3 within  Researchers’ Collection, 1 within History of Feinber), see: https://github.com/galterlibrary/digital-repository/pull/1143

Also related, the collection did not have any additional users that needed to be added, but if it did, they would have been added here: 
- communities.json in the galter-ir-importer github repo to include 8 additional users to the “Researcher’s Collection”, see: https://github.com/galterlibrary/galter-ir-importer/pull/129

**Comment by Meowcenary** [comment]
I'm closing this issue out since it seems like all the related PRs are now merged. We can re-open if necessary.
