### ISSUE TITLE
Remove non MeSH TopicalDescriptor from DH

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1145]
The 2022-11-17 import revealed that these records are using non-topical MeSH terms. Prism only supports topical MeSH terms. IIRC this was a decision from the metadata working group. We can revisit after launch.

The easiest thing to do would be to remove them from DH.

    fd27c6fe-a88e-4651-bfe6-f425ea0f44b6 -- https://id.nlm.nih.gov/mesh/D029282
    979ef868-01ad-4aca-929f-48a5bd37336b -- https://id.nlm.nih.gov/mesh/D064888
    97086eef-8a6e-42aa-9701-6e6d33c7d2fd -- https://id.nlm.nih.gov/mesh/D002363
    9b5cb4d2-ba02-44e7-84f2-61b35b27dd3c -- https://id.nlm.nih.gov/mesh/D005260
    ca398c56-3b51-4f39-9373-4f019e122a9f -- https://id.nlm.nih.gov/mesh/D015146
    fbbff015-a9fd-4729-a114-76c423853c37 -- https://id.nlm.nih.gov/mesh/D000073843

**Comment by gneidhardt** [comment]
These have been moved to keywords and out of MeSH: subject in DH.
