### ISSUE TITLE
Fix DOIs for Records

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#1147]
The DOI provider, dataacite, was experiencing some issues to their services. Resolve DOIs for:
- [x] https://digitalhub.northwestern.edu/files/72047eb7-48e3-4131-afdc-afa04b69281a
- [x] https://digitalhub.northwestern.edu/files/741e8145-0ef7-4ffc-8155-961772243b56
- [x] https://digitalhub.northwestern.edu/files/9749e5f5-1b1d-4a2e-8cd8-474ea41e416c
- [x] https://digitalhub.northwestern.edu/files/cbfa5273-f122-4d60-ae76-5dd1f7d1f9c9

**Comment by kglibrarian** [comment]
Did Dr. Kuang reach out to anyone with questions? I am guessing since these are NU only, there's no immediate need to send a DOI to a publisher (though, not saying the DOI isn't important of course). He has not emailed me or digitalhub@northwestern.edu yet.

**Comment by sharpattack** [comment]
For the bottom three records, I decided to copy over the DOIs that were created for them from datacite. 

Only draft state DOIs can be deleted, and these were already transitioned out of that state. You can never transition a DOI back to draft state so it can be deleted.
