### ISSUE TITLE
Update MeSH term mappings

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1151]
Just noting that affected files in DH have been changed. For reference, the relevant headings are below. None of the other revised headings had been assigned yet in DH, though we should keep them as potential headings for new items.

| ID | Old | New |
| --- | --- | --- |
| D001741 | African Americans | Black or African American |
| D000671 | Amputation | Amputation, Surgical |
| D001213 | Asian Americans | Asian |
| D044383 | Blacks | Black People |
| D000091202 | Health Disparity, Minority and Vulnerable Populations | Health Disparate, Minority and Vulnerable Populations |
| D006703 | Homeless Persons|  Ill-Housed Persons |
| D019651 | Reconstructive Surgical Procedures | Plastic Surgery Procedures |

**Comment by kglibrarian** [comment]
Adding this here for reference: 

Regarding new MeSH terms - typically, NLM does not retrospectively re-index MEDLINE citations with new MeSH heading concepts. 

Regarding terms that have changed (i.e. African Americans to Black or African American) the ID remains the same even if the term changes.
