### ISSUE TITLE
Review DH collections/communities 1st round

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#1158]

**Comment by sharpattack** [comment]
My task: 
- [ ] Check if there is script for retrieving list of collection owners in DH.

**Comment by sharpattack** [comment]
There is not script for retrieving list of collection owners in DH, but there is this: https://github.com/galterlibrary/galter-ir-importer/blob/master/data/communities.json

**Comment by kglibrarian** [comment]
I just finished this with a pull request where I updated the access permissions for some of the communities in the communities.json file. There are no new collections to report. If I am missing some step in this process, let me know, but I believe it's now finished. I will wait to close just in case there is more to this than I thought.

**Comment by sharpattack** [comment]
Thank you @kglibrarian! I think that this is all there is to this task. We can wait until that PR is reviewed and merged before closing this ticket.
