### ISSUE TITLE
Update New York (Colony) to New York (State)

### ISSUE THREAD

**Issue by Meowcenary** [galterlibrary/digital-repository#1160]
[This file](https://digitalhub.northwestern.edu/files/0e5436bb-270e-4320-860c-d61834cead23) incorrectly had the geographic term "New York (State)" map to "New York (Colony)". Update the memoized file to correct this and check for other potentially incorrect mappings.

**Comment by Meowcenary** [comment]
I'm going to check the memoized results of the last export run and it's log file to see if anything stands out to me as obviously wrong. If something is off we can discuss how best to approach fixing it.

**Comment by Meowcenary** [comment]
Here are the terms I've found that I think need further review:

- Belarus - https://id.loc.gov/authorities/names/n81008409.html
- Hungary - https://id.loc.gov/authorities/names/n50057161.html
- Poland - https://id.loc.gov/authorities/names/n82209573.html
- Romania - https://id.loc.gov/authorities/names/n81024614.html
- Malaysia - https://id.loc.gov/authorities/names/n82068163.html
- Kazakhstan - https://id.loc.gov/authorities/names/n80049642.html
- Russia - https://id.loc.gov/authorities/names/n80160431.html
- Yukon - https://id.loc.gov/authorities/names/n79141229.html
- Namibia - https://id.loc.gov/authorities/names/n80032137.html

**Comment by gneidhardt** [comment]
Hopefully it's helpful, but these should be:

- Belarus - https://id.loc.gov/authorities/names/n91128701.html
- Hungary - https://id.loc.gov/authorities/names/n79053090.html
- Poland - https://id.loc.gov/authorities/names/n79131071.html
- Romania - https://id.loc.gov/authorities/names/n79049551.html
- Malaysia - https://id.loc.gov/authorities/names/n79022246.html
- Kazakhstan - https://id.loc.gov/authorities/names/n92000005.html
- Russia - https://id.loc.gov/authorities/names/n80001203.html
- Yukon - this one actually is correct. I changed it to "Yukon Territory" in DH
- Namibia - https://id.loc.gov/authorities/names/n79039884.html

I think the problem with these is the Geographic Name autopopulates for us via API, but we can't see which source vocabulary it's pulling from (and I have no idea WHY say "Belarus" in DH, but push out to "Byelorussian S.S.R." in LCNAF).
