### ISSUE TITLE
Investigate Gretchen access to some GV Black records

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1175]
From https://github.com/galterlibrary/digitalhub-2/issues/486#issuecomment-1497825890 by Gretchen

[...] when I search for either the DOI or title (in quotes) in DH, I get zero results. I can see these in both of the GV Black collections, but I have go click on the collection and browse. Is this due to changes made to DigitalHub roles? I'm cc'ing @kglibrarian here too in case she knows something about why the GV Black stuff might be behaving in this way.

    10.18131/G3TW20 (3x0ts-td023)
    10.18131/G3FP48 (5vvme-8n365)
    10.18131/G3Q60D (qxc6d-yy321)
    10.18131/G37602 (57mzn-rzm35)
    10.18131/G33C76 (7qn5r-17b69)
    10.18131/G3KC7J (wzfr5-13n84)
    10.18131/G39W3Q (bzw18-jqm65)
    10.18131/G3ZP59 (epw73-tfn49)

**Comment by sharpattack** [comment]
I don't think this is an access issue. These items are created as a `Page` in the backend, and it looks like pages do not get indexed. So they can not be searched. I tested searching for a few other pages, from other collections as well. From the frontend, it is not easy to identify files as a Page or GenericFile. GenericFiles are what the majority of the records in DigitalHub are, and these do get indexed. 

If you have more records outside of the GV Black > Series IV. Photographs collection that do not appear in searches, please let me know and I will check if it is a Page or not. Closing.
