### ISSUE TITLE
Switch to mesh headings from an RDF file

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#133]
Figure out how to load it, db vs library.
http://id.nlm.nih.gov/mesh/

Check if we can store it in Fedora somehow...

**Comment by vioil** [comment]
This MESH RDF file should contain all of the MESH headings and possibly resource types. We should examine it and if true switch to using these URIs in our resource types.

**Comment by vioil** [comment]
After running a SPARQL I got the following results in HTML: http://id.nlm.nih.gov/mesh/describe?uri=http%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23PublicationType

We should get the URIs for each specific publication type (resource type) from the above link.

**Comment by phebal** [comment]
Remove Audio and Video from the resource type

**Comment by phebal** [comment]
I couldn't find MESH resource type counterpart for the following:
"Autobiography",
 "Controlled Clinical Trial",
 "Editorial Article",
 "Evaluation Study",
 "Interactive Tutorial",
 "Lectures",
 "Newspaper Article",
 "Patient Education Handout",
 "Speech"

I'm leaving them with the old URL until I'm told what to do.

**Comment by phebal** [comment]
Never mind, I'm starting to figure out how SPRQL works:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX mesh2015: <http://id.nlm.nih.gov/mesh/2015/>

SELECT distinct ?d ?dLabel 
FROM <http://id.nlm.nih.gov/mesh>
WHERE {
  ?d a meshv:PublicationType .
  ?d rdfs:label ?dLabel . 
} 
ORDER BY ?dLabel 
```

http://id.nlm.nih.gov/mesh/sparql?query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0D%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0D%0APREFIX+meshv%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23%3E%0D%0APREFIX+mesh%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%0D%0APREFIX+mesh2015%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F2015%2F%3E%0D%0A%0D%0ASELECT+distinct+%3Fd+%3FdLabel+%0D%0AFROM+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%3E%0D%0AWHERE+%7B%0D%0A++%3Fd+a+meshv%3APublicationType+.%0D%0A++%3Fd+rdfs%3Alabel+%3FdLabel+.+%0D%0A%7D+%0D%0AORDER+BY+%3FdLabel+%0D%0A&render=HTML&year=current&limit=1000&offset=0#lodestart-sparql-results

**Comment by phebal** [comment]
Query specific terms:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX mesh2015: <http://id.nlm.nih.gov/mesh/2015/>

SELECT distinct ?d ?dLabel 
FROM <http://id.nlm.nih.gov/mesh>
WHERE {
  ?d a meshv:PublicationType .
  ?d rdfs:label ?dLabel . 
  FILTER(REGEX(?dLabel,'^Abstracts$','i'))
 
} 
ORDER BY ?dLabel 
```

**Comment by vioil** [comment]
As per the decision of the DIWG we will not offer any audio or video files in the repository (at the beginning) so please remove the following resource types:

Instructional Films and Videos
Interactive Tutorial
Video-Audio Media
Webcast

**Comment by phebal** [comment]
Also removed:
Documentaries and Factual Films

**Comment by phebal** [comment]
Closing this ticket as it's became a dump-all resource related stuff while the gist of it has been addressed. I'll open a new ticket describing the remaining wish-list stuff.
