### ISSUE TITLE
Screen and only accept specific file types and sizes

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#141]
About.docx lists file types that we should be able to accept. Check the mime type and reject files that aren't in the acceptable formats.
Link video upload attempts to avalon, reach out to A.valon devs on them main campus.
Limit size to 200MB, have some docs that explain how and why

**Comment by phebal** [comment]
https://drive.google.com/folderview?id=0BxuFJij56yMQfmhZRzdQZDd1alh4VHRNX29UTmE4bXFsWEsxbDh3RnJlNHJBdndPWlJ6MHM&usp=sharing_eid&invite=CIzfseQO

**Comment by phebal** [comment]
Enabled front-end restriction to file extensions. Still need to do it in the back-end but that's less important.

**Comment by vioil** [comment]
:+1:
