### ISSUE TITLE
Change "Resource Type" multiselect box to a more modern, device-friendly control. 

### ISSUE THREAD

**Issue by jstirnaman** [galterlibrary/digital-repository#151]
Having to CTL-click may be confusing to some users.

**Comment by phebal** [comment]
Low priority, standard html form elements are normally preferred. Users actually know how to interact with them, due to experience with other forms. Custom form elements have their place but there have to be a very good reason to deviate.

**Comment by phebal** [comment]
Make the box bigger is the final decision.
