### ISSUE TITLE
FAST vocabulary integration into subjects (and keywords?) 

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#17]
Download the FAST subject headings from: http://www.oclc.org/research/activities/fast/download.html/?urlm=159755
We hope to integrate the FAST RDF (Linked Data Format N-Triples) format
Most likely we will need all files.

**Comment by phebal** [comment]
We went with LCSH for now. Closing.

**Comment by vioil** [comment]
@phebal  can you please remind me what was the issue with FAST on your end since both Tony and myself preferred FAST?

**Comment by phebal** [comment]
I don't remember. Duplicates I think?

**Comment by vioil** [comment]
this: #204

**Comment by phebal** [comment]
OK, so we are using FAST then....

**Comment by vioil** [comment]
let's talk about this in a meeting tomorrow
