### ISSUE TITLE
Change text in help bubbles

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#171]
Resource type
 - Pre-defined categories to describe the type of content being uploaded, such as "article" or “clinical trial." More than one type may be selected.

-
Title
 of the item - A name chosen by the depositor to aid in identifying the submitted content.  If not filled in, it will automatically default to the file name. This is a required field.

- Creator
 - (required field, automatically generated based on login information) – The person or group responsible for the content being submitted. Usually this is the author of the content. Personal names should be entered with the last name first, e.g. "Smith, John."
 This is a required field.

- Contributor
 - A person or group you want to recognize for playing a role in the creation of the content, but not the primary role. If there is a specific role you would like noted, include it in parentheses, e.g. "Jones, Mary (advisor)."

- Description
 - Free-text notes about the content or the file.  

- Abstract
- A summary statement about the file being deposited. For example,
 this may be a brief synopsis that accompanies a journal article, a conference presentation, or poster. The depositor can choose whether to use a “structured abstract” format (http://structuredabstracts.nlm.nih.gov/).

- Bibliographic citation
- A synopsis of information about the file that contains essential
 identifying information: author/s (creator/s), title, source (journal or book) or other identification (volume, pages, date, place of publication, if applicable). This information may vary based on the type of file being submitted. To see examples, refer to
 The NLM Style Guide for Authors, Editors, and Publishers (http://www.ncbi.nlm.nih.gov/books/NBK7256/).

- Keyword
(required field) - Word or phrase related to your work that you select
 to help interested users search for and locate your content. Note that the subject sections of the submission form provide lists of controlled vocabulary terms that can be used to describe the content of the file. Together “keywords” and “subjects” allow others
 to more easily discover a file in the repository.

- Rights
 (required field, see Creative
 Commons page for information)

- Publisher
 - The person or group making the work publicly available. Generally this is the institution - Galter Health Sciences Library, Feinberg School of Medicine, Northwestern University

- Date created
 - The date in which the work was originally published or otherwise made publicly available. Dates are accepted in the form YYYY-MM-DD, e.g. 1996-07-04.

- Subject: MeSH
- Controlled vocabulary terms developed by the U.S. National Library
 of Medicine. Suggestions are displayed as you type. . 

- Subject: LCSH
- Controlled subject vocabulary terms developed by the Library of
 Congress. Suggestions are displayed as you type. 

- Subject: Geographic Name
- Controlled geographic terms developed by the LIbrary of Congress.
 Suggestions are displayed as you type. Select a name of a geographic location (city, state, country, region, body of water, mountain range, etc.) which is one of the subject areas of the work, or which limits the scope of the work to a particular geographic
 area.

- Subject: Name
 - The Library of Congress Name Authority File (NAF) file provides authoritative data for names of persons, organizations, events, places, and titles. Suggestions are displayed as you type. Select a name of person, organizations, events, places, and titles.

- Language
 - The primary language in which the work was written. ISO639-2 standard is used. Suggestions are displayed as you type.

- Identifier
 - A unique string of characters such as DOI for a journal article, PubMed ID, PubMed Central ID, or an ISBN for a book. The type of identifier used should be entered in parentheses before the identifier itself, e.g. “(PMID) 26269873.

- Location
- The name of the location where the work was published or otherwise
 made available to the public. Calls upon the GeoNames web service (http://www.geonames.org).

- Related URL
 - A link to a website or other specific content (PDF document) related to the file, for example, the URL of a research project from which the file was derived or a dataset stored in a data repository.

- Digital origin
- system applied (for batch collections)

- Page number
- Numbers added by the submitter to each page or image, when creating
 a collection from a set of pages or images, to allow for orderly display in the image viewer.

**Comment by vioil** [comment]
Please double check the Resource type and Title since they appear to have the old definitions. 
:innocent:

**Comment by phebal** [comment]
OK, thanks for checking on this.
