### ISSUE TITLE
EndNote citation picking up a wrong link for the DOI field

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#190]
I think the link is coming from Fedora. Please check the Sufia config. 
See screenshot below:

![endnote1](https://cloud.githubusercontent.com/assets/3239996/9936930/f16df30e-5d23-11e5-9c08-8f5021a3753d.jpg)

**We need one of the Custom Fields to be named: Permanent Link and to pick up the link to the file**

**Comment by phebal** [comment]
Will need to modify the `ENV['FULL_HOSTNAME'] ` in production when we have a real name. Right now it's set to default server name.
