### ISSUE TITLE
Switch all resrouce types to MESH?

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#200]
Currently they're a mix of MESH and VIVO.

**Comment by vioil** [comment]
There are some classes from vivo that doesn't exist in NLM MESH. Let me check on this before you proceed.

**Comment by vioil** [comment]
You should leave the following from VIVO-ISF:
**Editorial Article**
**Speech**

**Comment by phebal** [comment]
I'll deal with this later. Thanks for checking on it.
