### ISSUE TITLE
Switch Geographic Subjects to FAST

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#204]
Currently loading but it's taking forever so might need to do something more custom.

**Comment by phebal** [comment]
Can't import, server running out of memory. Will come back to it on Monday.

**Comment by phebal** [comment]
Finally imported, but they're not showing up, not sure what's up.

**Comment by phebal** [comment]
Got them to show up and removed the duplicates that came from the rdf file.

**Comment by vioil** [comment]
:thumbsup:
:musical_note:
