### ISSUE TITLE
Featured works section should have the table like view even when not logged in, just like the Recently uploaded section

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#226]
See two screen captures for reference:

![notloggedin](https://cloud.githubusercontent.com/assets/3239996/10083399/e9b5bf3e-62c3-11e5-80c2-80642e673d08.jpg)

Should be like this section - Recently Uploaded:
![notloggedinru](https://cloud.githubusercontent.com/assets/3239996/10083400/e9b77bbc-62c3-11e5-9d01-6055de492916.jpg)

**Comment by phebal** [comment]
I think it should be the other way around, the table breaks in mobile view:
![recent_suf](https://cloud.githubusercontent.com/assets/3236815/10310430/91af4e5c-6c07-11e5-8751-1801ce6fd572.png)

This doesn't:
![featured](https://cloud.githubusercontent.com/assets/3236815/10310434/95d3f870-6c07-11e5-9d4f-6d396dfc0a57.png)
