### ISSUE TITLE
Adjust Rights to have help bubble and remove the Add button

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#232]
This is different in the batch and the file/collection edit form.

**Comment by phebal** [comment]
The add button issue and the help modal was fixed upstream, however, the field is still multi-value. We can fix it for us but it might cause some compatibility issues in the future. Basically it's a trad-off and we should probably leave it as a multi-value, unless it doesn't make sense. Does it ever make sense to have multiple licenses on a file?

**Comment by phebal** [comment]
Just to clarify, I think we should keep it as multi-value because it's assumed to be in various place in the code upstream and local.

**Comment by vioil** [comment]
In that case I think we should leave it as is to avoid future compatibility issues with the upstream project.

**Comment by phebal** [comment]
Relates to #239
