### ISSUE TITLE
Some files download automatically without opening in a new window

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#256]
compare this file: https://digitalhub.northwestern.edu/files/qb98mf449
with this one: https://digitalhub.northwestern.edu/files/6t053f96k

is it the file extension? I think only PDF and JPG behave as expected.

**Comment by phebal** [comment]
This actually is base on your browser. Some browser open things they can handle automatically. To save a file, right click and select 'Save link as..' at least in Firefox.
