### ISSUE TITLE
Creator field hiccups 

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#303]
When using the "creator" facet one can notice that the same user is listed twice depending on the order of the name - First Name Last Name OR Last Name, Middle Name First Name. 
You are not able to find all works by the same person. Use Justin B Starren example to see what is happening. This is not desirable behavior.
Here are the screenshots:

![justinbs](https://cloud.githubusercontent.com/assets/3239996/11244037/2afa43f6-8dd1-11e5-8eab-cb8feb848cc4.jpg)
![starrenbj](https://cloud.githubusercontent.com/assets/3239996/11244036/2af699e0-8dd1-11e5-836d-163a16a96030.jpg)

**Comment by phebal** [comment]
What's the solution here? Get rid of depositor?

**Comment by vioil** [comment]
I don't think that is the solution here. As you can see from the screenshot the creator field has two different values for the same person. That is not what we want - we want the creator value to be always the same for the that person. You can see other examples as well - I am in the repo as Violeta Ilik and as Ilik, Violeta and when you select one version of my name under the "creator" facet you get back only the items I have deposited with that version of my name.

**Comment by phebal** [comment]
OK, so I have the fix for it but the bad creators will still need to be adjusted manually.
