### ISSUE TITLE
 Upload folder button is not showing up for me (hebal) 

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#34]
Violeta Ilik says:
```
Piotr maybe it has to do with what type of resources you have chosen to upload in your collection? I have chosen most of the available types. Just a silly thought ... 
```

**Comment by vioil** [comment]
Is not showing up for Susan W. either

**Comment by phebal** [comment]
Problem is that all browsers other then Chrome are not supported.

**Comment by vioil** [comment]
thanks for updating this issue and apologies for not doing that myself when I discovered that only Chrome is supported.
