### ISSUE TITLE
Create a new facet: Rights Statement

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#340]
Pull from the Rights metadata field that we currently populate with CC licenses and few other options.

**Comment by phebal** [comment]
I don't understand what this means? I can only make a facet from things that our users chose for that particular field. @vioil can you please clarify?

**Comment by vioil** [comment]
@phebal - We have the "Rights" field and we control that field with values from Creative Commons and few other. Like wit any other facet we have you can create a facet based on the "Rights" field.

**Comment by phebal** [comment]
@vioil ok, that's clear enough, thanks. But what does the other part mean? Should it be in it's own ticket?

**Comment by vioil** [comment]
moved it to another ticket
