### ISSUE TITLE
Citations - pick up DOI

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#355]
The citations are working, they are picking up from all the fields that are needed for it: creator (tested with 4 different creators); title; location, publisher, date (only the year) 
Only the DOI needs to be picked up to have a complete citation. I will open a ticket for that.

**Comment by phebal** [comment]
Where is the DOI to go in each of the citation formats and what is it to look like. Can you give examples for each? Is it supposed to be like described in the email from Jason?
```
APA:
Author, A. A., & Author, B. B. Title of document [Format]. Retrieved from http://Web address
Roberts, K. F. Federal regulations of chemicals in the environment [PowerPoint slides]. Retrieved from doi://…
Chicago/MLA:
Author, A. A. Title. Medium. Date of access. DOI
Roberts, K. F. Federal regulations of chemicals in the environment. Web. Accessed January 1, 2016. Retrieved from doi://…
```

**Comment by vioil** [comment]
Not exactly like that. You use "Retrieved ..." in cases when you reference a webpage, not a DOI. 
It would look like this:

Article From an Online Periodical with DOI Assigned

Author, A. A., & Author, B. B. (Date of publication). Title of article. Title of Journal, volume number, page range. doi:0000000/000000000000 or http://dx.doi.org/10.0000/0000

Brownlie, D. (2007). Toward effective poster presentations: An annotated bibliography. European Journal of Marketing, 41, 1245-1283. doi:10.1108/03090560710821161

Wooldridge, M.B., & Shapka, J. (2012). Playing with technology: Mother-toddler interaction scores lower during play with electronic toys. Journal of Applied Developmental Psychology, 33(5), 211-218. http://dx.doi.org/10.1016/j.appdev.2012.05.005

**Comment by vioil** [comment]
For Chicago Manual of Style:

"The DOI in the following example indicates that the article was consulted online; it is preferred to a URL (see also 14.5, 14.6). Note that DOI, so capitalized when mentioned in running text, is lowercased and followed by a colon (with no space after) in source citations. Shortened citations for subsequent references to an online source follow the forms for printed books and journals.

**1. William J. Novak, “The Myth of the ‘Weak’ American State,” American Historical Review 113 (June 2008): 758, doi:10.1086/ahr.113.3.752.**

**Novak, William J. “The Myth of the ‘Weak’ American State.” American Historical Review 113 (June 2008): 752–72. doi:10.1086/ahr.113.3.752.**
"

**Comment by phebal** [comment]
What about MLA?
Also for Chicago format, should there be a comma or a period followed by a space before the DOI?

**Comment by vioil** [comment]
for all styles, including MLA please include the doi at the end after a comma and a space.
