### ISSUE TITLE
OSD doesn't work on mobile after upgrade to 6.5.0

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#358]
The openseadragon viewer does not work on mobile

**Comment by vioil** [comment]
how do you mean it doesn't work? works for me

**Comment by phebal** [comment]
It does? I guess it doesn't work on staging for some reason...

**Comment by vioil** [comment]
here is the screen shot 
![screenshot_2016-01-27-11-24-36](https://cloud.githubusercontent.com/assets/3239996/12622012/05c2ffca-c4e9-11e5-825d-e4de10e98694.png)
