### ISSUE TITLE
Prepopulate publishers?

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#464]
From Grid data or something.

**Comment by vioil** [comment]
take a look at #445

**Comment by sharpattack** [comment]
- prefill Publisher with "DigitalHub. Galter Health Sciences Library & Learning Center"

- Update user-facing instructions - "Entity(ies) responsible for the issuance, distribution or dissemination of the work, also typically the entity responsible for providing a DOI."

**Comment by sharpattack** [comment]
Not sure what the Grid Data is that is mentioned above, but going to assume it's this https://grid.ac/
Possibly meant for pre-populating the Location field.
