### ISSUE TITLE
Add PNB v.1-21

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#483]
the complete archive is in the box folder.

**Comment by phebal** [comment]
On it

**Comment by vioil** [comment]
please note that some of the older issues still don't have DOIs but will have them soon generated trough the PNB itself. Please if you run across those don't add them yet.

**Comment by phebal** [comment]
Will there be an updated xml issued or how we're going to know what those new DOIs are?

**Comment by vioil** [comment]
DOIs are in the XML file, they are just not officially registered but will be soon.

**Comment by phebal** [comment]
I'll wait with loading to production until they are registered. For now I'm trying to load them locally anyway.

**Comment by phebal** [comment]
Done

**Comment by vioil** [comment]
awesome!
