### ISSUE TITLE
Switch to global shib logout

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#485]
Latest news is that we do have a global logout services according to Xiaoxia:

>Here are the logout pages that your application could use. You will need both URLs to complete logout SSO pages.

 >https://websso.it.northwestern.edu/amserver/UI/Logout
 >https://fed.it.northwestern.edu/idp/profile/Logout

**Comment by vioil** [comment]
ok, this is great. hopefully this means that when i logout i don't need to close my browser to really logout

**Comment by phebal** [comment]
Well, if you click either of those links it says to close your browser. It's all very clunky and confusing. Users need to click both of those links, but they both say to close the browser. And there's no redirection. So how do we get users to click both of those links?

**Comment by phebal** [comment]
Looks like sticking `goto=` in the argument list is what does the trick. Here's how NUPA does it:

https://websso.it.northwestern.edu/amserver/UI/Logout?goto=http%3A%2F%2Fnupa.northwestern.edu%2Fpa91prod%2Fsignon.html

**Comment by phebal** [comment]
This is the link we want to use:

https://websso.it.northwestern.edu/amserver/UI/Logout?goto=https%3A%2F%2Ffed.it.northwestern.edu%2Fidp%2Fprofile%2FLogout
