### ISSUE TITLE
Some thumbnails are generated with a black background

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#488]
We need to fix the generation problem. Imagemagic is used to convert the pdf. The `-resize` option causes the black background. Problem is likely due to wrong colorspace being used for documents with CMYK colorspace. This works for example:
`convert -colorspace cmyk -resize 338x493 StatTag.pdf StatTag.jpg`
but not if you skip the colorspace directive. Problem is in detecting what colorspace to use.

Once fixed we need to regenerate thumbs for all pdfs at the very least.

**Comment by vioil** [comment]
if this is fixed, all the pnb copies that are also displaying black will be fixed, right?

**Comment by phebal** [comment]
Not at this time, this was a manual fix. I have a separate ticket for the root issue that's causing it. Once that's fixed then yes, hopefully.

On Thu, 2016-09-29 at 06:57 -0700, Violeta Ilik wrote:

if this is fixed, all the pnb copies that are also displaying black will be fixed, right?

**Comment by vioil** [comment]
I know this is manually fixed, I am asking, based on your analysis, if all PNB copies can be fixed as well considering what you discovered and think is the cause?

**Comment by phebal** [comment]
Yes, if (when) I fix the root cause and re-run the derivatives generation process they will be fixed along with any other black-background thumbnails.

On Thu, 2016-09-29 at 07:09 -0700, Violeta Ilik wrote:

I know this is manually fixed, I am asking, based on your analysis, if all PNB copies can be fixed as well considering what you discovered and think is the cause?

**Comment by phebal** [comment]
Whoops, I thought we were talking in the #487 ticket, that's why the confused messages. Perils of answering through email.

**Comment by phebal** [comment]
Found a fix for most cases of black background thumbs but while testing I discovered that there are sill times when we end up with a black bg. I'll investigate for a bit longer but the current fix should be good for > 90% of pdfs.

**Comment by phebal** [comment]
Fixing this for all images would involve adding `-alpha remove` commandline option to `convert` which imagemagic makes it anything but easy. We can talk about it tomorrow, for now I'll stop working on this.

**Comment by phebal** [comment]
This should be fixed for all pdfs now.
