### ISSUE TITLE
Upgrade from Fedora 4.2 to 4.5

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#491]
This will involve some data migration so it'll require a backup and needs to be done after hours. Maybe coordinated with our admins?

**Comment by phebal** [comment]
1. Put Fedora/Sufia down.
2. Take a backup of fedora data
3. Upgrade to Fedora 4.3.0
4. Migrate the changed file metadata
There are some utils to help with this, but they don't seems work and I'm not yet sure why:
https://github.com/fcrepo4-exts/fcrepo4-upgrade-utils
5. Bring up Sufia locally, don't allow public access and test
6. If everything is ok, allow public access else restore from backup and go back to brooding
7. Upgrade to Fedora 4.5 - no migration needed it seems

**Comment by phebal** [comment]
All this needs to be done on staging first.

**Comment by phebal** [comment]
Can migrate the data successfully but running into:
`403 STATUS: Objects cannot be created under pairtree nodes`
error when trying to create objects in the upgraded instance of Fedora.

Will try on a copy of production data to see if the same thing happens.

**Comment by phebal** [comment]
Metadata migration of the production data took 1m57.635s on my laptop, so it should take 5-10 minutes in production. Not bad.

**Comment by phebal** [comment]
Plan of migration that actually works, verified on a copy of production data:
1. Put Fedora/Sufia down.
2. Take a backup of fedora data
3. Migrate the changed file metadata
Migrate using:
https://github.com/fcrepo4-exts/fcrepo4-upgrade-utils
4. Bring up Sufia locally, don't allow public access, and test
5. If everything is ok, allow public access else restore from backup and go back to brooding
6. Upgrade to Fedora 4.5 - no migration needed it seems

**Comment by vioil** [comment]
when are you going to do this? don't do it on a friday :smile:

**Comment by phebal** [comment]
It's going to have to be not during the work hours. I think I'll wake up at 4 on Tuesday or Thursday and will do it then. I'll prepare everything ahead of time so I don't have to think much during the upgrade...

**Comment by phebal** [comment]
I'm planning to do it on Thursday, starting at 3am. I notified our sysadmins and asked them to coordinate.

**Comment by phebal** [comment]
Ticket in Footprints: 445741

**Comment by phebal** [comment]
Done, almost aborted the attempt because of a stray lock file in Fedora's data directory and java's terrible, unreadable logs but in the end it worked. We have a backup in case of any problems.
