### ISSUE TITLE
Sufia 7.x test server

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#493]
Bring up the latest Sufia version to see what it can do.

**Comment by phebal** [comment]
Done, also put one on the office 'server' so others can use.
http://galter-2310-1.fsm.northwestern.edu/

LDAP is not integrated so need to create accounts before logging in.

**Comment by phebal** [comment]
Let me know when you do log in so I can make you admins btw.

**Comment by vioil** [comment]
if LDAP is not integrated how can I log in?

**Comment by vioil** [comment]
ok, i logged in

**Comment by phebal** [comment]
OK, you're an admin now.
