### ISSUE TITLE
Move project arey to sufia?

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#494]
https://galter.northwestern.edu/digitized-projects/arey/

Currently it's on a Cold Fusion 'server' that needs to go away and should be moved somewhere. Is DH the right place for it?

**Comment by vioil** [comment]
ok, let's move it. this was on the list of things Ramune wanted in DH

**Comment by jstirnaman** [comment]
I looked over content on projects.galter.northwestern.edu again. I don't see any other candidates for DH. There are some [old library newsletters to migrate to the web site](https://github.com/galterlibrary/galter-website/issues/1488) and [one HTML app](http://www.rhodin.northwestern.edu/) that maybe should be moved somewhere else, but nothing that qualifies for the repository.

**Comment by jpastva** [comment]
Arey book is now in DH
