### ISSUE TITLE
Remove bot thwarting measures from httpd config when the attack stops

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#497]

**Comment by phebal** [comment]
They were back at it but just a single host. I blocked it and stored the new request pattern in the config file in case they're back in force. I just need to restart httpd.

**Comment by phebal** [comment]
In memory of the botnet attacking:
![dh-bot](https://cloud.githubusercontent.com/assets/3236815/19406040/5ede48de-9244-11e6-9a87-7119704059d8.png)

**Comment by vioil** [comment]
Thank you.

**Comment by phebal** [comment]
Botnet stats for Oct 13 13:20 until Oct 14 19:40:
Around 9,000 unique bots were and still are attacking.
They made 610,000 complex requests to `/catalog`.
We denied 362,053 of those requests.
Highest load on the server was more then 30.
Most request we handled in a minute was 5,520 on 14/Oct/2016:17:22

**Comment by phebal** [comment]
Botnet's last hurrah seemed to have been this morning where they managed to bring our reop down requesting catalog pages in a way that worked around my thwarting patterns. They seemed to have gone away now. I have 11,810 IPs blacklisted in case they return. I'll close this ticket when I remove those IPs and other protections from httpd config.
