### ISSUE TITLE
2016 collection

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#505]
images need to be made open access and the collection needs to move to institutional asap since the winners are announced as of last night.

**Comment by phebal** [comment]
I looked at this yesterday briefly and it was working. It still is. It must be something on your end...

I'm I to make this public today?

**Comment by phebal** [comment]
Whoops, I was responding to your first email, didn't see the edit.

Will do.

**Comment by vioil** [comment]
yes, today please. thanks!

**Comment by phebal** [comment]
This is done, I'm just going through images in the IIIF viewer now, trying to put them in cache as they put very large load on the server.
