### ISSUE TITLE
Add an IIIF manifest link for pagable collections

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#508]

**Comment by phebal** [comment]
I need an example what the manifest link should actually link to. Currently it generates IIIF Presentation API manifest:
http://iiif.io/api/presentation/2.0/

**Comment by vioil** [comment]
here is an example: http://digi.vatlib.it/view/Borg.ill.19
to see the IIIF manifest URI select the Read more button 

An example for a single image that I found on mirador.stanford.edu: http://dx.doi.org/10.7925/drs1.ucdlib_40851
It is originally from University of City of Dublin (UCD) and belongs in this collection: https://digital.ucd.ie/view/ucdlib:40377

**Comment by phebal** [comment]
Fixed via c97489f2d340f8920df2538dc1d4165dba471176
