### ISSUE TITLE
add audio file resource type

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#519]
from:
Display name: AudioVisualDocument 
IRI: http://purl.org/ontology/bibo/AudioVisualDocument

**Comment by vioil** [comment]
display name is not Audio Visual Document, it's the actual URI. Please fix.

<img width="743" alt="audiouri" src="https://cloud.githubusercontent.com/assets/3239996/21034140/0af1d5b2-bd7b-11e6-9e1a-33db65e846bb.png">

**Comment by phebal** [comment]
Whoops, will fix, sorry about it.
