### ISSUE TITLE
Migrate this collection: Northwestern University Medical School 1859-1979

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#527]
Northwestern University Medical School, 1859-1979 : a pioneer in educational reform / by Leslie B. Arey. 
http://www.galter.northwestern.edu/digitized-projects/arey 
For the record, see: http://nucat.library.northwestern.edu/cgi-bin/Pwebrecon.cgi?BBID=7256526 

Full MARC record: 

000	01443cam a22003613u 4500
005	20161011104413.0
006	m        d f      
007	cr unu---uuuuu
008	141120s1979    ilua    s     00110 eng d
001	9972565264202441
035	  |a(IEN)7256526-nwudb
040	  |aIEN|cIEN
043	  |an-us-il
050	04|aR747.N862|bA84 1979
082	 4|a610/.7/117731
100	1 |aArey, Leslie Brainerd,|d1891-
107	2 |aNorthwestern University (Evanston, Ill.).|bMedical School.
245	10|aNorthwestern University Medical School :|b1859-1979, a pioneer in educational reform /|cby Leslie B. Arey.
250	  |aRev. and extended.
260	  |aEvanston [Ill.] :|bNorthwestern University,|c©1979.
300	  |aonline resource :|billustrations.
336	  |atext|btxt|2rdacontent
337	  |acomputer|bc|2rdamedia
338	  |aonline resource|bcr|2rdacarrier
530	  |aAlso available in a print version.
588	  |aDescription based on print version record.
500	  |aIncludes index.
610	20|aNorthwestern University (Evanston, Ill.).|bMedical School.|xHistory.
610	22|aNorthwestern University (Evanston, Ill.).|bMedical School.
650	 2|aSchools, Medical|xhistory.
651	 2|aChicago (Ill.)
776	18|iPrint version:|aArey, Leslie Brainerd,|d1891-|tNorthwestern University Medical School, 1859-1979|w(DLC)   79126269|w(OCoLC)5990419|w991185184202441
948	  |aclone|bk|c20080516
INT	  |aE
INST	  |a01NWU_INST

PNX record:

<record xmlns="http://www.exlibrisgroup.com/xsd/primo/primo_nm_bib" xmlns:sear="http://www.exlibrisgroup.com/xsd/jaguar/search">
<control>
<sourcerecordid>51592491980002441</sourcerecordid>
<sourceid>01NWU_ALMA</sourceid>
<recordid>01NWU_ALMA51592491980002441</recordid>
<originalsourceid>01NWU_INST</originalsourceid>
<sourceformat>MARC21</sourceformat>
<sourcesystem>Alma</sourcesystem>
<almaid>01NWU_INST:51592491980002441</almaid>
</control>
<display>
<type>book</type>
<title>
Northwestern University Medical School : 1859-1979, a pioneer in educational reform
</title>
<creator>Arey, Leslie Brainerd, 1891-</creator>
<edition>Rev. and extended..</edition>
<publisher>Evanston Ill. : Northwestern University</publisher>
<creationdate>©1979</creationdate>
<format>online resource : illustrations..</format>
<subject>
Northwestern University (Evanston, Ill.). Medical School -- History; Northwestern University (Evanston, Ill.). Medical School; a Chicago Medical College; b Feinberg School of Medicine; Schools, Medical -- history; Chicago (Ill.)
</subject>
<language>eng</language>
<source>01NWU_ALMA</source>
<lds06>Includes index.</lds06>
<lds06>Also available in a print version.</lds06>
<lds06>Description based on print version record.</lds06>
<lds15>
Northwestern University Medical School : 1859-1979, a pioneer in educational reform
</lds15>
<lds16>Northwestern University</lds16>
<lds22>
Northwestern University Medical School : 1859-1979, a pioneer in educational reform / by Leslie B. Arey.
</lds22>
<lds23>by Leslie B. Arey.</lds23>
</display>
<search>
<creatorcontrib>Leslie Brainerd, Arey 1891-</creatorcontrib>
<creatorcontrib>Arey, Leslie Brainerd, 1891-</creatorcontrib>
<creatorcontrib>Arey, L</creatorcontrib>
<creatorcontrib>by Leslie B. Arey.</creatorcontrib>
<title>
Northwestern University Medical School : 1859-1979, a pioneer in educational reform /
</title>
<subject>
Northwestern University (Evanston, Ill.). Medical School. History.
</subject>
<subject>
Northwestern University (Evanston, Ill.). Medical School.
</subject>
<subject>
nnaa Northwestern University, Evanston, Ill. Medical School, Chicago
</subject>
<subject>a Chicago Medical College</subject>
<subject>b Feinberg School of Medicine</subject>
<subject>Schools, Medical history.</subject>
<subject>Medical Colleges</subject>
<subject>nnna Medical School</subject>
<subject>Medical Schools</subject>
<subject>nnna School, Medical</subject>
<subject>g Academic Medical Centers</subject>
<subject>g Schools, Health Occupations</subject>
<subject>Chicago (Ill.)</subject>
<general>Northwestern University,</general>
<general>Includes index.</general>
<general>Also available in a print version.</general>
<general>Description based on print version record.</general>
<sourceid>01NWU_ALMA</sourceid>
<recordid>01NWU_ALMA51592491980002441</recordid>
<rsrctype>book</rsrctype>
<creationdate>1979</creationdate>
<startdate>19790101</startdate>
<enddate>19791231</enddate>
<addtitle>Northwestern University Medical School, 1859-1979</addtitle>
<addsrcrecordid>9972565264202441</addsrcrecordid>
<searchscope>01NWU_ALMA</searchscope>
<searchscope>01NWU_INSTALL</searchscope>
<searchscope>01NWU_INSTLaw</searchscope>
<searchscope>01NWU_INSTNUL</searchscope>
<searchscope>01NWU_INSTGalter</searchscope>
<searchscope>01NWU_NUL</searchscope>
<searchscope>01NWU_ONLINE</searchscope>
<searchscope>01NWU</searchscope>
<scope>01NWU_ALMA</scope>
<scope>01NWU_INSTALL</scope>
<scope>01NWU_INSTLaw</scope>
<scope>01NWU_INSTNUL</scope>
<scope>01NWU_INSTGalter</scope>
<scope>01NWU_NUL</scope>
<scope>01NWU_ONLINE</scope>
<scope>01NWU</scope>
<lsr14>Evanston [Ill.]</lsr14>
<lsr15>Northwestern University,</lsr15>
<lsr16>(IEN)7256526-nwudb</lsr16>
</search>
<sort>
<title>
Northwestern University Medical School : 1859-1979, a pioneer in educational reform /
</title>
<creationdate>1979</creationdate>
<author>Arey, Leslie Brainerd, 1891-</author>
<lso01>197913</lso01>
</sort>
<facets>
<language>eng</language>
<creationdate>1979</creationdate>
<topic>
Northwestern University (Evanston, Ill.). Medical School–History
</topic>
<topic>
Northwestern University (Evanston, Ill.). Medical School
</topic>
<topic>Schools, Medical–history</topic>
<topic>Chicago (Ill.)</topic>
<toplevel>online_resources</toplevel>
<prefilter>books</prefilter>
<rsrctype>books</rsrctype>
<creatorcontrib>Arey, Leslie Brainerd</creatorcontrib>
<atoz>N</atoz>
<classificationlcc>
R - Medicine.–Medicine (General)–Medical education. Medical schools. Research
</classificationlcc>
<newrecords>20150718_30</newrecords>
<frbrgroupid>316945167</frbrgroupid>
<frbrtype>5</frbrtype>
</facets>
<dedup>
<t>2</t>
<c5>9972565264202441</c5>
<f5>1</f5>
<f6>1</f6>
<f10>1</f10>
<f11>1</f11>
<f20>9972565264202441</f20>
</dedup>
<frbr>
<t>1</t>
<k1>$$Karey leslie brainerd 1891$$AA</k1>
<k3>
$$Knorthwestern university medical school^book^eng$$AT
</k3>
</frbr>
<delivery>
<institution>01NWU</institution>
<delcategory>Alma-E$$I01NWU</delcategory>
</delivery>
<enrichment>
<classificationlcc>R747.N862</classificationlcc>
</enrichment>
<ranking>
<booster1>1</booster1>
<booster2>1</booster2>
</ranking>
<addata>
<aulast>Arey</aulast>
<aufirst>Leslie Brainerd,</aufirst>
<au>Arey, Leslie Brainerd</au>
<btitle>
Northwestern University Medical School : 1859-1979, a pioneer in educational reform
</btitle>
<date>1979</date>
<risdate>1979</risdate>
<format>book</format>
<genre>book</genre>
<ristype>BOOK</ristype>
<cop>Evanston [Ill.]</cop>
<pub>Northwestern University</pub>
<mis1>51592491980002441</mis1>
</addata>
<browse>
<author>
$$DArey, Leslie Brainerd, 1891-$$EArey, Leslie Brainerd, 1891-$$I41-LIBRARY_OF_CONGRESS-n 80001137$$PY
</author>
<title>
$$DNorthwestern University Medical School : 1859-1979, a pioneer in educational reform$$ENorthwestern University Medical School : 1859-1979, a pioneer in educational reform
</title>
<subject>
$$DSchools, Medical -- history$$ESchools, Medical history$$TMESH$$I2441-OTHER-341663$$PY
</subject>
<subject>
$$DMedical Colleges$$EMedical Colleges$$TMESH$$I2441-OTHER-341663$$PN
</subject>
<subject>
$$DMedical School$$EMedical School$$TMESH$$I2441-OTHER-341663$$PN
</subject>
<subject>
$$DMedical Schools$$EMedical Schools$$TMESH$$I2441-OTHER-341663$$PN
</subject>
<subject>
$$DSchool, Medical$$ESchool, Medical$$TMESH$$I2441-OTHER-341663$$PN
</subject>
<subject>
$$DAcademic Medical Centers$$EAcademic Medical Centers$$TMESH$$I2441-OTHER-341663$$PR
</subject>
<subject>
$$DSchools, Health Occupations$$ESchools, Health Occupations$$TMESH$$I2441-OTHER-341663$$PR
</subject>
<subject>
$$DNorthwestern University (Evanston, Ill.). Medical School -- History$$ENorthwestern University (Evanston, Ill.). Medical School. History$$TLCNAMES$$I41-LIBRARY_OF_CONGRESS-n 84204964$$PY
</subject>
<subject>
$$DNorthwestern University (Evanston, Ill.). Medical School$$ENorthwestern University (Evanston, Ill.). Medical School$$TMESH
</subject>
<subject>
$$DNorthwestern University, Evanston, Ill. Medical School, Chicago$$ENorthwestern University, Evanston, Ill. Medical School, Chicago$$TLCNAMES$$I41-LIBRARY_OF_CONGRESS-n 84204964$$PN
</subject>
<subject>
$$DChicago Medical College$$EChicago Medical College$$TLCNAMES$$I41-LIBRARY_OF_CONGRESS-n 84204964$$PR
</subject>
<subject>
$$DFeinberg School of Medicine$$EFeinberg School of Medicine$$TLCNAMES$$I41-LIBRARY_OF_CONGRESS-n 84204964$$PR
</subject>
<subject>$$DChicago (Ill.)$$EChicago (Ill.)$$TMESH</subject>
<institution>01NWU</institution>
</browse>
</record>

**Comment by jpastva** [comment]
This collection is now in DH
