### ISSUE TITLE
add COAR logo on the DH page

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#535]
logo attached

![member_of_coar_logo_final_png_800px](https://user-images.githubusercontent.com/3239996/27159976-6add49bc-5136-11e7-955e-d72b58112c0c.png)

maybe best place is by the Login button 

<img width="1342" alt="ribon" src="https://user-images.githubusercontent.com/3239996/27160083-1e770594-5137-11e7-9106-7d07faba6a4c.png">

**Comment by sharpattack** [comment]
@kglibrarian @kaars can we get a decision on placement of this logo?
