### ISSUE TITLE
Export all descriptive metadata for DigitalHub

### ISSUE THREAD

**Issue by jpastva** [galterlibrary/digital-repository#536]
Hi,

I'd like to take a look at the way users are applying descriptive metadata for all items in DigitalHub, excluding collections and hierarchical items. I'm interested the main fields that are visible on the public interface, including:

- Title
- Resource Type
- Keywords
- Rights
- Creator
- Contributor
- Description
- Abstract
- Original Bibliographic Citation
- Related URL
- Digital Publisher
- Original Publisher
- Date Created
- Original Identifier
- Language
- Subject: MeSH
- Subject: LCSH
- Subject: Geographic Name
- Location
- DOI
- Private Note

If possible, it would be great to view this as a spreadsheet/csv with one row for each record. I can take a look at some other possible outputs if necessary to see what works best. It would be great to have something by the end of Aug. at the latest if possible.

Thanks!

**Comment by phebal** [comment]
Sent via email. @jpastva please reopen the ticket if there are problems with the file.

**Comment by jpastva** [comment]
@phebal Looks great! Thanks!

**Comment by jpastva** [comment]
Could I get an updated version of this file, again in csv format? Would it also be possible to include some of the administrative info - Depositor, Date Uploaded, and Date Modified?

**Comment by phebal** [comment]
File sent in email. I've automated the generation of the csv file. Script is in:
`/home/deploy/scripts/subject.csv.rb`

**Comment by jpastva** [comment]
Can I get another export of this file, to include everything in DigitalHub up to the present? Thanks!

**Comment by sharpattack** [comment]
File with data up to November 5, 2018 sent.

**Comment by sharpattack** [comment]
per @jpastva 

>  It would be good know, as we’re working on some metadata cleanup, whether a resource is public or private.

Script has been updated to include Read Access Group
