### ISSUE TITLE
What to do with keywords

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#54]
Currently the GVB collection doesn't have any keywords and thus it doesn't feature in the cloud on the front page. Should we treat subjects as keywords?

**Comment by vioil** [comment]
We can treat subjects as keywords so the keywords can be featured in the cloud.

**Comment by vioil** [comment]
DIWG comment: not a priority

**Comment by phebal** [comment]
Partially addressed by making the word cloud pull from 'All Subjects' facet. We need to now figure out if we should remove the keywords and/or subject fields as at least one of them is not really needed. I'll close this ticket as it's a dupe of #121
