### ISSUE TITLE
Switch to gem-based passenger

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#548]
This way we can address bugs and handle updates ourselves in a timely manner.

**Comment by phebal** [comment]
For more information look here:
https://github.com/galterlibrary/galter-website/issues/1662#issuecomment-262069884

Keep in mind that this is for switching both rvm and passenger to local. Also passenger in this example is not version controlled with Gemfile like in our current website set-up. Look at the deployment scripts for the website if you want to see how that was done. Passenger deployment and configuration, and upgrades should be via capistrano.

**Comment by phebal** [comment]
One other thing to keep in mind is that puppet might be getting in your way on staging/production.

**Comment by sharpattack** [comment]
@phebal do we want to use latest passenger gem version `5.2.0`? or use same as website, version `5.1.11`?

**Comment by phebal** [comment]
Latest available IMO @sharpattack
