### ISSUE TITLE
Resource type for the GVB collection

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#55]
Currently there's no resource type for this collection, what should it be if anything?

**Comment by vioil** [comment]
various resource types - I'll work on this

**Comment by vioil** [comment]
How about we use either:
"http://purl.org/ontology/bibo/PersonalCommunicationDocument"
OR: 
http://purl.org/ontology/bibo/Letter
For the Collection: Series II. Correspondence between G.V. Black and F.S. McKay on mottled enamel of teeth

**Comment by vioil** [comment]
DIWG comment: not a priority

**Comment by vioil** [comment]
resource type for all images is Image
resource type for correspondence is Letter

We cannot use BIBO classes since we removed those us options
Please check with Tony for the other works in the collection

**Comment by phebal** [comment]
All series 1items are Manuscript
Series 2: Collection Correspondence
Series 3: Ephemera
