### ISSUE TITLE
Check for animated GIF support

### ISSUE THREAD

**Issue by jpastva** [galterlibrary/digital-repository#550]
Determine if/how to support preview display of animated GIF file. Currently, user must click "download the file" link in order to view animation (see https://digitalhub.northwestern.edu/files/dbaffe67-13f5-469b-b7d8-6f427c6f2a99). This seems fine, but it would be great to have a "play" button option similar to that available for mp4 files, such as this record: https://digitalhub.northwestern.edu/files/4de23834-0309-48f9-9b9b-05dbaa6940ec

Will email a copy of the GIF file

Thanks!

**Comment by phebal** [comment]
So I can't really do a play button, but I can do a compressed looping gif like so:
https://vtfsmghslrepo01.fsm.northwestern.edu/files/0dab5499-0e84-48f0-9796-dd67a326fdc5

What do you think @jpastva ?

**Comment by jpastva** [comment]
I think that looks pretty cool :)
Seems to be what Sara Grady was hoping for.

**Comment by phebal** [comment]
Done:
https://digitalhub.northwestern.edu/files/dbaffe67-13f5-469b-b7d8-6f427c6f2a99

Note that, if you've viewed that link before you'll need to clear your cache
