### ISSUE TITLE
Get stats for Science in Society images

### ISSUE THREAD

**Issue by jpastva** [galterlibrary/digital-repository#551]
Just got this request from Sara Grady, coordinator of the scientific images contest:

"I’m curious to see the view and download rates for each of our winning images over the whole collection. I can see them individually in the “analytics” tab of each image, but I’d love a matrix or tables in which I can compare them. Is there any way this sort of information can be pulled form the backend for multiple artifacts at once?"

Not sure if this is possible? It would be great to get to this as soon as possible.

Thanks!

**Comment by kristiholmes** [comment]
we haven't promoted the collection, which will likely be reflected in the stats.  I saw an article about the images on Twitter and thought about linking to the collection in a retweet. Does it seem like this would be well-received?

**Comment by jpastva** [comment]
Sounds like a good way to highlight DH's role in preserving the images. I believe Sara is working on an article about one of the images being used as a textbook cover, and she was hoping to have a look at the DH usage stats for more context. Should be a good way to promote the 2017 images!

**Comment by kristiholmes** [comment]
terrific, thanks!

**Comment by phebal** [comment]
There's no easy way to do this but I'll find a way to pull the data out of Googleanalytics somehow.

**Comment by phebal** [comment]
[dl_view_stats_per_month.zip](https://github.com/galterlibrary/digital-repository/files/1616444/dl_view_stats_per_month.zip)

@jpastva Please see attached. It lists view and download stats per month since the files were uploaded.

**Comment by jpastva** [comment]
Looks great! I'll let you know if I need anything else. Thanks!

**Comment by phebal** [comment]
Great, closing. Please feel free to re-open if anything else is required.
