### ISSUE TITLE
error page when attempting to remove user roles

### ISSUE THREAD

**Issue by jpshank** [galterlibrary/digital-repository#553]
i was trying to give Mark (mbe582) & Kristi (klh183) access to the the Stats page, and mistakenly gave them the role "admin," when all they actually needed to view that page is the role "editor". Now when I try to remove them from the admin role https://digitalhub.northwestern.edu/roles/1/edit I get an error screen. 

probably not a big deal that they're admins, but I know that role allows you to edit almost everything, so probably better for that role to be removed from their accts. i also assigned them the correct role "editor".

**Comment by phebal** [comment]
Thanks, the permissions are fine, we should all be admins IMO. I'll look at the error though, thanks for reporting.
