### ISSUE TITLE
Elevate Collection

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#559]
per @lodwyer:
> 
> I've created a new collection in DigitalHub to house capstone project papers from the Masters in Public Health program. For now, I'll be depositing these papers myself but eventually we would like an MPH administrator to have access to this collection for deposit purposes.
> 
> Could the collection be elevated so that it shows up in the Collections tab?

**Comment by sharpattack** [comment]
Create Institutional Collection titled "Student's Collection" and move MPH collection here.

**Comment by lodwyer** [comment]
Thanks, Austin. Just to be clear, it should be named: Students' Collections

**Comment by sharpattack** [comment]
@lodwyer and @jpastva this is done and the changes are in production now. Can you please inspect it and update/edit the metadata when you get a chance? Please let me know if anything looks odd.

**Comment by lodwyer** [comment]
Thanks, Austin. Could you pluralize "Collection" in "Students' Collection"?

**Comment by sharpattack** [comment]
"Collection" is now pluralized @lodwyer. Sorry, I only saw the apostrophe correction in your previous comment.
