### ISSUE TITLE
Allow for LDAP-driven selection of creator and contributor

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#56]
Currently these are free-form. How should we limit those? Should we make people select form LDAP fetched results? Should only owners/proxies be allowed to set creators? contributors?

**Comment by vioil** [comment]
Yes, fetch from LDAP results - that was the original plan for both fields (creator and contributor). Yes, I think it's best to have only owners/proxies set creators/contributors

**Comment by vioil** [comment]
Format names as shown below:
Last Name, First Name Middle Name (Initial)
