### ISSUE TITLE
Remove collection from Researchers' Collections

### ISSUE THREAD

**Issue by jpastva** [galterlibrary/digital-repository#561]
I'm not sure how if/how I managed this, but the collection "2017 Scientific Images Contest Winners" currently appears in two high-level collections - Science in Society Scientific Images Contest and Researchers' Collections. It can be removed from Researchers' Collections.

Thanks!

**Comment by sharpattack** [comment]
I believe this is because the depositor is not "institutional-(something)". 

@phebal do we want to change the behavior to check if the collection returns `true` on the `institutional_collection` column, instead of checking who the depositor is?

**Comment by sharpattack** [comment]
Answer to my own question: no, we don't want to change the behavior. The depositor has to be "institutional-(something)". Will be converting the collection @jpastva mentions above to be Institutional this afternoon.
