### ISSUE TITLE
Elevate researcher's collection to stand-alone collection

### ISSUE THREAD

**Issue by kglibrarian** [galterlibrary/digital-repository#563]
Elevate the Center for Community Health's collection out of “researchers’ collections” and into a stand-alone collection. 

Current collection: https://digitalhub.northwestern.edu/collections/ae0b945c-d0d4-45bb-a0fc-263c7afca49e
Use the collection name: Center for Community Health

Permission granted via email from Grisel Robles-Schrader on 02/06/2018. 

Let me know if you need any additional information!

**Comment by sharpattack** [comment]
To convert the Center for Community Health into an institutional collection, the depositor will be changed. Checking with the original depositor, Keith Alan Herzog, to get his consent and understanding of this effect. 

@kglibrarian please let us know when you get an answer.
