### ISSUE TITLE
Information for NUCATS Newsletter

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#564]
Per @kaars and @kglibrarian

Due: April 15, 2018 

Information and statistics about DigitalHub for upcoming news item needed. 

- [ ] How are statistics caclulated?
- [ ] In-depth description of analytics provided for each item
- [ ] define "pageview" and "download"
- [ ] explain any additional information that can be provided by contacting DigitalHub

**Comment by sharpattack** [comment]
@kaars @kglibrarian regarding some of the questions above. 

- In the first question, can you clarify which statistics you are referring to? Is this from the admin view? Or from a User dashboard view? 
- The in-depth description of analytics, is this for per file/object? 
- The "pageview" and "download" is for per file/object, right?

**Comment by kglibrarian** [comment]
I'll try! I'm guessing these questions came about from the article I will be writing in 1 -2 months for the DigitalHub communication plan?  The article is to help the user better understand the type of data/analytics they can get from DigitalHub. So the statistics would be referring to any statistics/analytics that the user can view - so views and downloads and anything else in the dashboard view. I think that users can only see analytics for items (correct?), so we'd be discussing items-level analytics in the article. If there is an option to show analytics for the collection-level, that would be great to know and share with our users. Hope that helps! Also, I think we also discussed that the analytics/statistics for the user on their profile page were not working.
