### ISSUE TITLE
Add functionality to follow a collection in DigitalHub

### ISSUE THREAD

**Issue by kglibrarian** [galterlibrary/digital-repository#572]
If possible, it would be nice for people to "follow a collection" in DigitalHub, either from their profile page (similar to following an author) or setting up an email alert for whenever something new is added to a collection.

**Comment by phebal** [comment]
Adding this type of functionality would require extending `acts_as_follower` gem. Currently the gem only accepts `ActiveRecord::Base` type objects. We need it to take `ActiveFedora`. It's not a quick fix, but doable. It would take a few days to implement so I'll talk to my team to see if we can spare the time to make this happen.

**Comment by kaars** [comment]
@kglibrarian, what priority would you give to this issue? Has this come up
in conversations with multiple users? Just trying to determine whether we
should spend the necessary time on it for DigitalHub.

Thanks,

Matt

**Comment by kglibrarian** [comment]
I can't recall how many times I've heard it, but it was not many - perhaps once or twice when I was demo-ing DigitalHub at the seminar we had last summer for program assistants, etc. More so, I think it would be a feature that our Centers would like - because they can encourage their followers to keep up -to-date when they upload new versions of protocols or surveys, or when they are making new content available to their followers. But again, it's just a wish list item. If you have other stronger priorities - those take precedence. It makes "selling" the idea of creating a collection to a Center easier, though.

**Comment by kglibrarian** [comment]
With this in particular, we may not have heard it much because we don't have many users creating collections, let alone institutional-level collections. So there wouldn't have been many opportunities to hear it.

**Comment by kaars** [comment]
Ok, thanks. We'll put it on the list.
