### ISSUE TITLE
Add Altmetric donut to DigitalHub item pages

### ISSUE THREAD

**Issue by kglibrarian** [galterlibrary/digital-repository#574]
Patty had a great idea (that we may have looked into in the past, but I can't find a ticket for it) to look into adding the Altmetric donut to our DigitalHub pages. 

Here's the information: 

https://www.altmetric.com/products/free-tools/institutional-repository-badges/

**Comment by sharpattack** [comment]
Support ticket to add our domains to altmetric. 

https://help.altmetric.com/support/tickets/64847
