### ISSUE TITLE
Hyperlink DOIs to preferred resolver

### ISSUE THREAD

**Issue by katrinleinweber** [galterlibrary/digital-repository#582]
Hello!

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). There are several `.erb` files that link DOIs against the old one. If these can be savely changed, I'd be happy to send a PR.

Cheers :-)

**Comment by phebal** [comment]
Hello Katrin,

Great, thanks for bringing this to our attention. We'd appreciate any help you can provide. I see no issues with changing the resolver URL, @sharpattack please let me know if you agree.

**Comment by sharpattack** [comment]
I agree @phebal, I think that any help we can get would be great. Thanks @katrinleinweber.

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)
