### ISSUE TITLE
Check currency of LCSH and LCNAF data sources and update if needed

### ISSUE THREAD

**Issue by jpastva** [galterlibrary/digital-repository#608]
Investigate the currency of the vocabularies used to autocomplete Subject: Name and Subject: LCSH. If we are not pulling from the live Library of Congress linked data service for the Library of Congress Name Authority File (LCNAF), or the Library of Congress Subject Headings (LCSH), these vocabularies should be updated, and regular updates should be scheduled going forward. Monthly would be ideal.

See also #520, which should be updated on an annual basis.

**Comment by phebal** [comment]
I agree, we gotta make this an automatic process somehow. It won't be easy, I'll discuss with my team.

**Comment by sharpattack** [comment]
for reference 
https://id.loc.gov/techcenter/searching.html

**Comment by sharpattack** [comment]
https://www.oclc.org/developer/develop/web-services/fast-api/linked-data.en.html
