### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#62]
so we can see the usage stats and patterns.

**Comment by vioil** [comment]
DIWG comment: not a high priority

**Comment by phebal** [comment]
Hmm, I think that we should probably get this working prior to lunch as it'll tell us how the website is being used. I can parse something from the logs but nothing close to what GA provides...

**Comment by vioil** [comment]
This should definitely be ready for launch. Not sure how the group convinced me to mark it "not a high priority"
