### ISSUE TITLE
Create institutional-level collection for Oncofertility Consortium

### ISSUE THREAD

**Issue by kglibrarian** [galterlibrary/digital-repository#624]
**Background information:** We need an institutional-level collection for the Oncofertility Consortium to deposit items from their upcoming conference (see here: https://oncofertility.northwestern.edu/annual-oncofertility-consortium-conference). In addition, it seems they have ideas for other oncofertility related items that will be uploaded because those items have difficulty being published in traditional journals. We think they may want to create their own web interface for the collection and simply link to the items in DigitalHub. This would give them the freedom to create something similar to their current interface (see their Resource Browser: http://oncofertility.northwestern.edu/search/site). Though, the specifics still need to be worked out with their IT staff. At some point, we may need to create sub-collections for each volume or year (the specifics still need to be worked out). They will be using mediated deposit where someone from their group will be responsible for uploading all the items because not all of the authors/creators are from Northwestern. We will be meeting with Lauren Ataman, our contact for the group, on Thursday, September 6, 2018 (the time is yet to be determined) to further discuss this project. 

**Collection Information:** 
Title: Dialogues in Oncofertility
Authors/Owners: Laruen Ataman (lauren.ataman@northwestern.edu); Brigid Smith (brigid.smith@northwestern.edu); Teresa Woodruff (tkw@northwestern.edu)
Description: to be determined
Keywords: to be determined

Does it matter if we add sub-collections later on, or do you need to know all of that ahead of time? 

**Preferred due date**: Thursday, September 6 by 12 pm, because we're meeting with them between 12 and 3 pm, and I'd like to show them their collection. However, if that isn't possible, then we can hold off until after the meeting.

**Comment by sharpattack** [comment]
@kglibrarian we should be able to have it ready as an institutional collection by tomorrow. 

For sub collections, that can always be added at a later date, and can be done by us(your team/my team).

**Comment by kglibrarian** [comment]
I just found out that their IT group is not available for a meeting tomorrow. So now they're looking into next week for a date/time. So there's less of a rush on it now. Thank you for your help with this group!!

**Comment by kglibrarian** [comment]
Lauren emailed me today (9/24/2018) at 10 am stating she'd like to upload six items to this collection this week. Would it be possible to have this collection ready to go for her soon?
