### ISSUE TITLE
Batch metadata field updates

### ISSUE THREAD

**Issue by jpastva** [galterlibrary/digital-repository#634]
List of metadata fields to be changed in DigitalHub in batch if possible:

-All items with "Pediatric Neurology Briefs Publishers" in the Original Publisher field --> Add additional field to Digital Publisher with "Pediatric Neurology Briefs Publishers" and delete from Original Publisher
-All items in Science in Society Collection - delete "Science in Society" from Original Publisher
-All DigitalHub items - delete "Chicago, Illinois, United States" and delete "Chicago, IL, USA" from Location

It would be great if this could be done in next 2 months. Thanks!

**Comment by sharpattack** [comment]
@jpastva some questions: 

Does "all items" include updating the relevant fields for Collections too? For the first list:
> All items with "Pediatric Neurology Briefs Publishers" in the Original Publisher field 

Does this also apply to Collections with that value in the Original Publisher field? 


For "all DigitalHub items", is this not limited to just the items we're updating above?

> All DigitalHub items - delete "Chicago, Illinois, United States" and delete "Chicago, IL, USA" from Location

Updating ALL items? Including Collections, private/personal, non-Galter managed items and collections?

**Comment by jpastva** [comment]
@sharpattack 

> All items with "Pediatric Neurology Briefs Publishers" in the Original Publisher field

 Includes collections fields

> All DigitalHub items - delete "Chicago, Illinois, United States" and delete "Chicago, IL, USA" from Location

Applies to all items, including collections. It's not likely that private and non-Galter managed items will have values in these fields, but yes, that's the plan

**Comment by sharpattack** [comment]
Estimates Report:
> All items with "Pediatric Neurology Briefs Publishers" in the Original Publisher field --> Add additional field to Digital Publisher with "Pediatric Neurology Briefs Publishers" and delete from Original Publisher
- updated: 4.1k items

> All DigitalHub items - delete "Chicago, Illinois, United States" and delete "Chicago, IL, USA" from Location
- updated: 4.5k items

> All DigitalHub items with Digital Publisher value "Galter Health Sciences Library, Feinberg School of Medicine, Northwestern University" --> change to "Galter Health Sciences Library"
- updated: 100+ items

**Comment by sharpattack** [comment]
@jpastva latest export is uploaded to box.

**Comment by jpastva** [comment]
@sharpattack thanks!
