### ISSUE TITLE
Create institutional-level collection for NUCATS Grants Repository

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#636]
·         Title/Name of collection: NUCATS Grants Repository
·         Brief description of the entire collection: Funded grant proposals, templates, and stock language for Northwestern investigators
·         Keywords for the entire collection:  grant proposals, research support, peer-reviewed grants
·         Creators/Owners: Keith Herzog, Emily Traw, and Jaime Ziegler 
·         Visibility for Collection: Northwestern Only

**Comment by kglibrarian** [comment]
Can you create 4 subcollections with these titles: R01, R03, R21, and K-series

**Comment by sharpattack** [comment]
Yes, will add them. All of the Creators/Owners listed above will have full permissions to these subcollections as well.

**Comment by sharpattack** [comment]
@kglibrarian can I add the same keywords for the subcollections as the parent? These can be changed/updated later if needed.

**Comment by sharpattack** [comment]
@kglibrarian this is done. The Creators/Owners should see the collections listed.

**Comment by kglibrarian** [comment]
Never mind. Figured out how to do this on my own.
