### ISSUE TITLE
Move metadata extraction script to this project

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#644]
Currently, the script is just living on the server in a folder. It should be a part of this project's repository, with instructions to run it. 

Related to #536

**Comment by carsonicator** [comment]
Thanks, Austin. @jpastva the output is in the Metadata Subcommittee Box folder (https://northwestern.app.box.com/folder/64951771085/all_gf_subject.csv). Is this what you were wanting?

**Comment by jpastva** [comment]
That's it. Thanks!
