### ISSUE TITLE
Batch field update - Publisher

### ISSUE THREAD

**Issue by jpastva** [galterlibrary/digital-repository#654]
Perform batch update on all Publisher fields in all records in DigitalHub as follows:

- If field equals "Galter Health Sciences Library", update to - DigitalHub. Galter Health Sciences Library.  (including private records) 
- If field equals "Galter Health Sciences Library & Learning Center", update to - DigitalHub. Galter Health Sciences Library & Learning Center  (including private records) 
- If field is empty && record is NOT private, add "DigitalHub. Galter Health Sciences Library & Learning Center"

**Comment by fenekku** [comment]
There can be multiple publishers for the publisher field. What happens then? (There are not multiple publishers on CD2H project for now- nevertheless important to know for DigitalHub)

**Comment by jpastva** [comment]
Entries with multiple publishers should be retained, not replaced, but any fields containing Galter Library should be updated as outlined above. Our discussions about this field have included an assumption that we will continued to allow multiple Publisher entries in the new repo. If this turns out not to be the case, we will need to evaluate records with multiple publishers (including the Pediatric Neurology Briefs collection, which is quite large).

**Comment by sharpattack** [comment]
Question: are we adding "DigitalHub. Galter Health Sciences Library & Learning Center" to all "Publisher" fields that do not have it?

Answer: For existing records with blank Publisher fields, we can add "DigitalHub. Galter Health Sciences Library & Learning Center," but only if they're public.

@jpastva what level of public? Open Access or Northwestern Only?

**Comment by jpastva** [comment]
@sharpattack public includes open access and Northwestern. Exclude anything else marked as "private"

**Comment by sharpattack** [comment]
Depends on #656
