### ISSUE TITLE
Disable Original Publisher field

### ISSUE THREAD

**Issue by jpastva** [galterlibrary/digital-repository#655]
Disable Original Publisher field, and transfer values to Digital Publisher field. As of the creation of this ticket, there were no values in the Original Publisher field. Ideally this merge will happen ASAP to prevent any further use of the Original Publisher field.

**Comment by sharpattack** [comment]
@jpastva are we removing the "Original Publisher" field? And renaming "Digital Publisher" to "Publisher"? 

How about adding "DigitalHub. Galter Health Sciences Library & Learning Center" to all "Publisher" fields that do not have it, do we want to do this? Or just going forward, prefill the field?

**Comment by jpastva** [comment]
@sharpattack yes, Original Publisher will be removed, and Digital Publisher will be renamed as Publisher. I wasn't sure whether "merge" was correct terminology, in case any new values pop up in Digital Publisher in the short term.

For existing records with blank Publisher fields, we can add "DigitalHub. Galter Health Sciences Library & Learning Center," but only if they're public.
