### ISSUE TITLE
Merge (?) contributors in DigitalHub

### ISSUE THREAD

**Issue by kristiholmes** [galterlibrary/digital-repository#662]
There are two versions of me in DIgitalHub.  Sometime when you have a moment (**_no rush at all_**), can you take a look and let me know how to best resolve this?

- most recent records [HERE](https://digitalhub.northwestern.edu/catalog?depositor=%22klh183%22&f%5Bcreator_sim%5D%5B%5D=Holmes%2C+Kristi&q=holmes)
- older records [HERE](https://digitalhub.northwestern.edu/catalog?depositor=%22klh183%22&f%5Bcreator_sim%5D%5B%5D=Holmes%2C+Kristi+Lee&q=holmes)

in both cases, the depositor was klh183 (my NetID)

**Comment by sharpattack** [comment]
For the Creator field, it looks like the NU directory/LDAP lookup has been updated/removed middle names some time last summer. I see the more recent records do not include "Lee", and doing a search in the Creator field does not return it either. 

If it's not too much, we can have someone from the metadata team go and update this. I see at most 21 for "Kristi Lee Holmes", and 11 for "Kristi Holmes". I am guessing we want just "Kristi Holmes", right @kristiholmes ?

Or, we can create a script to update these fields. This would provide better coverage, but the sample size seems small enough that having someone go in and update the fields would be a quicker route. 

@jpastva what do you think? Do we have someone to assign this task to?

**Comment by jpastva** [comment]
@sharpattack is it that LDAP isn't including middle names? Or just that Kristi's directory record no longer includes her middle name in the public display? I just realized that I am in the same boat - I have some earlier records in DH that include my middle name, and some that don't. At some point I figured out how to remove my middle name from the NU directory and updated my record, so that explains the change.

Perhaps this "instability" of the name feed from LDAP merits further discussion. In any case, we can definitely update Kristi's records.

**Comment by sharpattack** [comment]
@jpastva I meant it looks like the record for Kristi in LDAP directory has been updated. It will return middle names, if it's there. If you removed yours from LDAP, then that is the culprit of your case. I am guessing/hoping that's the case with Kristi too. 

It can be discussed whether to include middle names or not, seeing how it can affect things later.

Thank you for taking care of this. Feel free to close when the creator/contributor field for Kristi's name has been updated.

**Comment by jpastva** [comment]
All of the "Kristi Lee Holmes" entries have been changed to "Kristi Holmes." Let me know if any were missed.

**Comment by kristiholmes** [comment]
Thanks, Joelen and Austin! Just logging into gmail now and saw this
exciting update! :-)
Appreciate your help!
Kristi
