### ISSUE TITLE
Add "Study Design" Resource Type

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#685]
Requested per Liping Song and Eileen Wafford.

**Comment by sharpattack** [comment]
URI: https://id.nlm.nih.gov/mesh/D012107

**Comment by saragon02** [comment]
Instead of Research Design, please use "**Study Design**." Use DDI definition, found on this page: https://ddialliance.org/Specification/DDI-CV/LifecycleEventType_1.0.html

Per DIWG Metadata Subcommittee meeting, 2019/11/19.

**Comment by sharpattack** [comment]
Thanks @saragon02 for the update and link to the definition.
