### ISSUE TITLE
Add subcollections for Center for Data Science and Informatics

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#709]
Add the following subcollections:

### 1. Chicago Biomedical Informatics and Data Science Jam
_Copy over metadata from https://digitalhub.northwestern.edu/collections/a58d0b93-df89-4f10-9064-fa4e99b79bb1._ 
_Visibility level of the collection:_ Northwestern Only

### 2. Biomedical Data Science Day
_Description:_ The Center for Data Science and Informatics presents Biomedical Data Science Day. A one-day event of data science talks and interactive code sessions intended for all levels of programming experience and statistical knowledge from newcomer to advanced.

_Related URL:_ https://www.nucats.northwestern.edu/resources/data-science-and-informatics/biomedical-data-science-day.html

_Keywords:_ “biomedical science”, “data science”

_Visibility level of the collection:_ Open Access

- 2a. **2020** _(subcollection)_
  - _Description:_ The Center for Data Science and Informatics presents Biomedical Data Science Day. A one-day event of data science talks and interactive code sessions intended for all levels of programming experience and statistical knowledge from newcomer to advanced.
  - _Related URL:_ https://www.nucats.northwestern.edu/resources/data-science-and-informatics/biomedical-data-science-day.html
  - _Keywords:_ “biomedical science”, “data science”
  - _Visibility level of the collection:_ Open Access

Dependent upon completion of #703

**Comment by kglibrarian** [comment]
I've completed my portion of this ticket.
