### ISSUE TITLE
Update to Emergency Ribbon

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#735]
From Ann Crago, to be ready by 2pm today. 

> we’re going to be updating the line to the following:
>  
> Coronavirus information for [Northwestern Memorial Hospital](https://www.nm.org/conditions-and-care-areas/infectious-disease/novel-coronavirus), [Lurie Children’s Hospital](https://www.luriechildrens.org/en/news-stories/novel-coronavirus-covid-19-resources/), [Northwestern University](https://www.northwestern.edu/coronavirus-covid-19-updates/) and [CDC](https://www.cdc.gov/coronavirus/2019-nCoV/index.html).

We should also update to include the ribbon on all pages. It currently only appears on the home page.

**Comment by carsonicator** [comment]
By request from Ann Crago, we need to update the emergency banner to read:

> Coronavirus information for [Feinberg](https://www.feinberg.northwestern.edu/sites/covid-19/).

See link for exact format.
