### ISSUE TITLE
DigitalHub Collections to InvenioRDM Communities mapping

### ISSUE THREAD

**Issue by carsonicator** [galterlibrary/digital-repository#750]
@kglibrarian and @carsonicator will meet and work on a couple of tasks:

- [ ] Modeling DigitalHub's multi-layered collections with the two-tiered system provided by InvenioRDM
- [ ] Try to resolve multiple resource type issues 

According to CERN, (exposed*) community metadata is minimal for now but includes:

- Title
- Community Image
- Description
- Permissions (private and public only)
- The communities available to the user can be returned in a search

For collections, which are subcategories underneath communities, there is just a header at this point.

`*`: It is possible to add metadata to community in the long run but in the short run no. Collections have no plan for further metadata.

**Comment by fenekku** [comment]
Actually done a while ago. Closing.
