### ISSUE TITLE
Upgrade sufia to 6.7

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#766]

**Comment by Meowcenary** [comment]
Seems like #763 is pretty similar. I'm not sure if there is any advantage to using github versus a version number for the Gemfile, but I personally prefer a version number. Obviously this isn't a pressing issue, but if we don't plan on using a version number we mine as well close the ticket.

**Comment by sharpattack** [comment]
Yep, this was done in #765. We could not use the version number because the latest changes were not tagged and released.

**Comment by Meowcenary** [comment]
Oh, I see.
