### ISSUE TITLE
Export User Info

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#770]
Output to csv file.

**Comment by sharpattack** [comment]
Update to include: 
- number of files deposited (can leave blank if they've deposited nothing or make it 0)
- last deposit date (if available)

**Comment by Meowcenary** [comment]
@sharpattack , this is what you're actively working on right? I'm trying to get a handle on how much we have left to cover for the sake of estimations.

**Comment by sharpattack** [comment]
Thanks @Meowcenary, this was fell off my radar, but it should be a quick-win. I will take care of this soon.
