### ISSUE TITLE
Export Collections Keywords and Subject: MeSH

### ISSUE THREAD

**Issue by saragon02** [galterlibrary/digital-repository#771]
Request for a CSV export of DigitalHub Collections and all sub-collections' Keywords and Subject: MeSH terms/

**Comment by sharpattack** [comment]
@saragon02 working on this today. In addition to Tags(displayed as Keywords to the user) and Mesh, are there any other metadata/headers that should be included? I plan to include Title, and a link to the collection. Unless these are unnecessary, just let me know.

**Comment by saragon02** [comment]
@sharpattack Title and collection link would be great to have as well, thanks! Those are all the fields I should need.
