### ISSUE TITLE
Contact FSMIT Transfer DigitalHub Images To Invenio Server

### ISSUE THREAD

**Issue by Meowcenary** [galterlibrary/digital-repository#781]
Ask FSMIT how best to approach moving all record images from DigitalHub to Invenio. Some ideas that were brought up were SCP or Rsync, but there is probably a standard approach that FSMIT takes for this sort of thing. Maybe a good time to bring it up is at the next support call?

**Comment by fenekku** [comment]
Closed per https://github.com/galterlibrary/digitalhub-2/issues/19

IT told us to use rsync (no special way).
