### ISSUE TITLE
Export Invenio Files Field

### ISSUE THREAD

**Issue by Meowcenary** [galterlibrary/digital-repository#783]
**Feb 2021 Edit**

As of writing, all of the files metadata is actually generated by InvenioRDM when uploading a file. So this metadata doesn't have to be generated to export/upload the file. The actual JSON file needed is just this one from the REST API request: https://inveniordm.docs.cern.ch/reference/rest_api/#start-draft-file-uploads . That being said, given Katie's integrity requirement (really our own too) keeping track of the checksum so that we can compare it against the uploaded file would be needed. This could be kept track of in this extra JSON that ties things together.

**Comment by fenekku** [comment]
We have a single file per record in digitalhub so this should be straightforward.

**Comment by sharpattack** [comment]
Putting this on hold. 

It's not clear where the contents of the files exactly are on the server. Once their location is found, how is it mapped to the record?

Some questions:
1. What's our best option for handling files? I think using invenioRDM's rest API so it can handle the file metadata. It would reduce the number of steps needed if we could directly use the rest API on the server to upload the file. 
2. We could download each file, but how slow is this? 
3. What digest algorithm is used on digitalhub?

**Comment by sharpattack** [comment]
File's contents located. It is based on their SHA1 checksum, which is also the digest algorithm used. 

With that said, I am going to add the needed JSON for files, and let the api take care of the metadata.
