### ISSUE TITLE
Export Invenio Ext Field

### ISSUE THREAD

**Issue by Meowcenary** [galterlibrary/digital-repository#786]
Export the [top level field](https://inveniordm.docs.cern.ch/reference/metadata/#overview) `ext` from the Sufia format to the Invenio format. Use the following as test data to verify the end result:

```
        "ext": {
            "dwc": {
                "collectionCode": "abc",
                "collectionCode2": 1.1,
                "collectionCode3": True,
                "test": ["abc", 1, True]
            }
        }
```

**Comment by fenekku** [comment]
This has to do with https://inveniordm.docs.cern.ch/develop/make_it_your_own/#extend-the-metadata-model . This functionality has been disabled temporarily, so we can deprioritize this field (although it will be needed). 

The extended metadata the subcommittee came up with are listed starting on line 135 of this document:

https://docs.google.com/spreadsheets/d/1UzVNMaKYgzhwjIx_ib4_-JDPbxsI50ZBq1I5X2ExU00/edit#gid=0

That document is a little dated and if it's not clear yet, we should consolidate the various documents we have.

The mapping to digitalhub 2 extended metadata hidden is in this document (along with mapping of normal field, which is dealt with separately):

https://northwestern.app.box.com/file/684887467855?s=1e1ogwnz4vrh7upmrlfuf3nk4vw1ap64

**Comment by fenekku** [comment]
n/a now closing
