### ISSUE TITLE
Export resource types [revisit] 

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#831]
In the export excerpt and in the export zip so far, the resource types are not always filled in:

```json
    "resource_type": {
        "type": null,
        "subtype": "Pictorial Work, Photograph"
    },
```

The resource types should match up with the resource type conversion. See documents linked here: https://github.com/galterlibrary/digital-repository/issues/787#issuecomment-747463195 . 

So the above example should actually look like:

```json
    "resource_type": {
        "type": "image",
        "subtype": "image-pictorial_work"
    },
```

**Comment by sharpattack** [comment]
@fenekku there are some DigitalHub resource types that map to more than one possible InvenioRDM resource type. What would be the best way to approach this? i.e. "Academic Dissertations" can be either "Bachelor Thesis", "Masters Thesis", or "Doctoral Thesis". Can `subtype` be omitted? After migration, experts can select the correct subtype on examination.
```
    "resource_type": {
        "type": "thesis"
    },
```

**Comment by saragon02** [comment]
@sharpattack @fenekku, the above approach should work, as long as reports can be generated listing the records on which this approach was taken so the CMMS staff will know exactly which records to go back and examine for resource type clean-up later.

**Comment by fenekku** [comment]
@sharpattack Right now `subtype` can be omitted because of an unrelated technical reason. This reason should be going away by the time we do the export and the possibility of omitting `subtype` with it. Combining what @saragon02 suggested would be ideal: we could return `"subtype": "thesis-bachelor_thesis"` in all cases where only a thesis is present and keep note of these cases in a separate file to manually re-assess later.

**Comment by sharpattack** [comment]
Okay, then I will take the first mentioned subtype mapping where there's multiple listed.
