### ISSUE TITLE
Export Metadata Subfields Related Identifiers (aka Related Works)

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#834]
Export related identifiers / related work: per https://inveniordm.docs.cern.ch/reference/metadata/#related-identifiers-0-n
The recent changes in resource_type affects this too.

**Edit 2021-06-16**
As of writing, the current implementation accepts this structure:

```json
{
  "related_identifiers": [{
      "identifier": "10.1234/foo.bar",
      "scheme": "doi",
      "relation_type": "cites",
      "resource_type": {"id": "dataset"}
  }, ...],
}
```

Notice that **relation_type** should be used and not just **relation**.

However, it is likely that in the future (per this issue https://github.com/inveniosoftware/invenio-rdm-records/issues/635), the structure will be:

```json
{
  "related_identifiers": [{
      "identifier": "10.1234/foo.bar",
      "scheme": "doi",
      "relation_type": {"id": "cites"},
      "resource_type": {"id": "dataset"}
  }, ...],
}
```

So let's go with that structure. On my side, the import can adapt to whatever the reality is. 
The identifier and scheme part is ok for now.

**Comment by sharpattack** [comment]
We will use related_url. 

Couple Questions: 
- What is the scheme? Is it limited to the following list? 
  - ISBN10, ISBN13, ISSN, ISTC, DOI, Handle, EAN8, EAN13, ISNI ORCID, ARK, PURL, LSID, URN, Bibcode, arXiv, PubMed ID, PubMed Central ID, GND, SRA, BioProject, BioSample, Ensembl, UniProt, RefSeq, Genome Assembly.
- What is the relation? Can it be some generic text? 
- What is the resource_type? This is not required.

**Comment by sharpattack** [comment]
Example record with a related_url, but possibly not on the scheme list. 
https://digitalhub.northwestern.edu/files/j3860692c

**Comment by fenekku** [comment]
Answers:
- Schemes are indeed picked from that list. Anything from the deposit page dropdown is included. `PURL` / `URN` in that list implies `URL` but it should indeed be official. As of writing, the supported list is:

```python
    SCHEMES = [
        "ark",
        "arxiv",
        "bibcode",
        "doi",
        "ean13",
        "eissn",
        "handle",
        "igsn",
        "isbn",
        "issn",
        "istc",
        "lissn",
        "lsid",
        "pmid",
        "purl",
        "upc",
        "url",
        "urn",
        "w3id"
    ]
```

![image](https://user-images.githubusercontent.com/1932651/122389631-21175a80-cf3f-11eb-9274-755026771ef0.png)

- The relation type is a controlled vocabulary. As of writing it is:

```python
    RELATIONS = [
        "iscitedby",
        "cites",
        "issupplementto",
        "issupplementedby",
        "iscontinuedby",
        "continues",
        "isdescribedby",
        "describes",
        "hasmetadata",
        "ismetadatafor",
        "hasversion",
        "isversionof",
        "isnewversionof",
        "ispreviousversionof",
        "ispartof",
        "haspart",
        "isreferencedby",
        "references",
        "isdocumentedby",
        "documents",
        "iscompiledby",
        "compiles",
        "isvariantformof",
        "isoriginalformof",
        "isidenticalto",
        "isreviewedby",
        "reviews",
        "isderivedfrom",
        "issourceof",
        "isrequiredby",
        "requires",
        "isobsoletedby",
        "obsoletes"
    ]
```

The resource_type is the same as the other top-level resource type (see that one for reference).

**Comment by sharpattack** [comment]
We will go with `isRelatedTo` now, and handle any needed changes during import.
