### ISSUE TITLE
Revisit Metadata Subfield Licenses

### ISSUE THREAD

**Issue by Meowcenary** [galterlibrary/digital-repository#856]
The next release of InvenioRDM will have updates to the metadata subfield licenses. Check for any updates that need to be made and implement those changes.

**EDIT 2021-05-28**

Licenses ("rights" field) should be like this:

```json
{
  "record": {
    "metadata": {
      "rights": [{
        "id": "CC-BY-3.0-US",
        "link": "http://creativecommons.org/licenses/by/3.0/us/",
        "title": "Creative Commons Attribution 3.0 United States"
      },
      ...
    }
  }
}
```

modified to appropriate licenses. Valid `id`s can be found here: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/licenses.csv

**Comment by sharpattack** [comment]
Since `id` is required, and we don't have a mapping for "All Rights Reserved", we will use `GALTER--ARR-1` for these cases.
