### ISSUE TITLE
Revisit Metadata Subfield Subjects

### ISSUE THREAD

**Issue by Meowcenary** [galterlibrary/digital-repository#857]
The next release of InvenioRDM will have updates to the metadata subfield subjects. Check for any updates that need to be made and implement those changes.

**EDIT 2021-06-18**
The new subjects structure:

```json
{
    "subjects": [{
        "id": "D001921",
      }, 
      ...
    ],
}
```

For MeSH we will use the MeSH identifier (e.g. "D001921" as above). 
For FAST, we will use its identifier as a string (e.g. "862474")
For other subjects (if any) a proper identifier should be chosen.

All extra subject information like its human readable label will be loaded on the instance side.

**Comment by fenekku** [comment]
Probably the june release will have those changes.

**Comment by Meowcenary** [comment]
We are going to hold off on this until after the July 4th holiday so that we can discuss any remaining fields with the full team.

The remaining fields for subjects are:

- Geographic Name - The source is FAST - Geographic. NOT being migrated :ballot_box_with_check:
- Name - The source is LCNAF, Library of Congress Name Authority File. NOT being migrated :ballot_box_with_check:


Regarding geographic name vs location from slack:

"...in our mapping on [Box](https://northwestern.box.com/s/1e1ogwnz4vrh7upmrlfuf3nk4vw1ap64), and the InvenioRDM data model outline [Google Doc](https://docs.google.com/spreadsheets/d/1UzVNMaKYgzhwjIx_ib4_-JDPbxsI50ZBq1I5X2ExU00/edit?usp=sharing). In metadata subcommittee discussions we confirmed that DH Location has been used as a presentation location field, as in this [record](https://digitalhub.northwestern.edu/files/6f032b75-efdb-4ff9-8154-7443b2cac1e0), while location in InvenioRDM refers to the geographical place the record is about."

**Comment by sharpattack** [comment]
Don't forget keyword/tags 😄 

As for Geographic Name, this will be used in the `Locations` invenioRDM metadata instead. 
We need to add LCNAF, as it is expected to be migrated.

**Comment by Meowcenary** [comment]
Thanks for the follow up. I think I might cut this branch after some more debugging and then create a new ticket for that work. Idk though. It would be just for organization really.

**Comment by sharpattack** [comment]
Sounds good to me, let's separate the work for Subject Name/LCNAF. I have already added a commit for keywords/tags, sorry about that. 
Seeing the updated documentation for uncontrolled vocabularies, tags will need to be formatted like the following(with our custom "galter-keyword" label): 
``` ruby
{
    "subjects": [{
        "subject": "galter-keyword-<keyword>",
      }, 
      ...
    ],
}
```

**Comment by fenekku** [comment]
As of 2021-07-08, the structure for subjects in a record is:

**controlled vocabulary subject (has an id)**

```json
{
    "subjects": [{
        "id": "<subject id - see notes below>",
      }, 
      ...
    ],
}
```

**uncontrolled vocabulary subject**

```json
{
    "subjects": [{
        "subject": "<subject value>",
      }, 
      ...
    ],
}
```

The 2 can be mixed and matched:

```json
{
    "subjects": [{
        "subject": "<subject value>",
      }, {
        "id": "<another subject id>"
      ...
    ],
}
```

The `id` is a string that is if possible the URI of the subject. For example, for MeSH it would be: 

`"id": "https://id.nlm.nih.gov/mesh/D000001"`

If the id is not a URI, just put it in e.g. `"id": "310607"` for ANZSRC . This is not my preferred approach but that's the way it was decided for now.
