### ISSUE TITLE
Additional Description and Title Refactor

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#887]
Refactor and abstract `#additional_description` and `#additional_title` to one method. 

Also need to fix current implementation as it returns `[]` for one title or description value.

For those with no values, what do we want to return? Do we completely omit `additional_titles` and `additional_descriptions`, or: 

Empty array
``` ruby
additional_titles: []
```

**Comment by sharpattack** [comment]
Upon closer look, returning empty array `[]` with only one, or less, title or description was the correct implementation. After the first value, any extra values were the 'additional' ones that belonged here.

**Comment by fenekku** [comment]
That commit isn't associated with a PR yet, but I will give some comments right away in the commit.
