### ISSUE TITLE
Export record permissions

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#896]
Although InvenioRDM doesn't support per user permissions yet (it will with communities), we will have to export the DigitalHub ones eventually.

The kind of information we want to capture is

- what permission(s)
- given to whom -- user(s) identified by netid(s) / email(s)

A reasonable structure for now is:

```json
{
  ...,
  "extras": {
    "permissions": {
      "edit": ["<user identifier>", ...]
      "view": [...]
    }
  }
} 
```

This is not a blocker for the initial export apriori. If we decide to wait to import when communities exist, then this should be part of that import. By then, the structure of these kinds of permissions will also be established and we will be able to use them. If we don't wait, the importer should be able to map that basic information from the `extras.permisions` into what InvenioRDM wants.

**Comment by Meowcenary** [comment]
Austin has submitted a PR for this so I'm reassigning to him and moving to the correct column.
