### ISSUE TITLE
List netid Instead of Group Name In Exported Permissions

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#903]
In the "extras" portion of the export, the group name is listed with it's permission type. This may not be useful if we do not perserve/transfer the group name and it's members in Prism. If not, add each group member to their respective permission type.

**Comment by fenekku** [comment]
This depends on https://github.com/galterlibrary/digital-repository/issues/902 .

**Comment by sharpattack** [comment]
This was already completed in PR #903. Syntax was incorrect when linking multiple issues. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
