### ISSUE TITLE
Update perform_and_parse

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#913]
For both LCSH and MeSH query lookups. Right now, we are setting the id/uri to the first returned result. It may not be the query. 

i.e. Using "cancer" vocabulary, the current `#perform_and_parse_mesh_query` will return "Abdomen--Cancer" as the first result, and we end up pairing "cancer" with the id of "Abdomen--Cancer".

**Comment by Meowcenary** [comment]
The approach we have decided to use is to store the LCSH and MeSH terms into two YAML files with the following format:

**MesH**
```
- id: https://id.nlm.nih.gov/mesh/D000001
  scheme: MeSH
  subject: Calcimycin
``` 
**LCSH**
- id: http://id.loc.gov/authorities/subjects/sh2008122899
  scheme: lcsh
  subject: Kitchens--Planning
```

Instead of querying MeSh or LCSH lookup APIs we will instead search these files for the necessary data and cache the results of lookups to the previous file that was used for caching subject header lookups.
