### ISSUE TITLE
Add New Org to KnownOrganizations

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#921]
Add "Northwestern University (Evanston, Ill.). Women's Health Research Institute" to the list.

**Comment by kglibrarian** [comment]
Is there a list of organizations for Northwestern? I can review these against variants in Web of Science and Scopus. I'm just not sure what this is in reference to? We also have a fairly long list of institutes and centers from a recent review of the Feinberg website.

**Comment by fenekku** [comment]
@kglibrarian It refers to this list of creators/contributors that should be identified as institutions when exporting them to Prism:
https://github.com/galterlibrary/digital-repository/blob/694414877366cc0236181cfd9fd37f451cbd6ced/app/models/concerns/galtersufia/generic_file/known_organizations.rb

Do you have another list handy that could complement this list?

**Comment by sharpattack** [comment]
Thank you for getting that, @fenekku ! 
@kglibrarian these "Organizations" are what was already in DH, and refers to creators and contributors. Since there is not a way to "label" a creator/contributor as a person or organization, we just have a long list of names. @Meowcenary did a good job here identifying whether a creator/contributor is an organization, so we can label them as such when migrating.

**Comment by sharpattack** [comment]
I see you already answered the "refers to" question, @fenekku Sorry for the duplicate response 🤦
