### ISSUE TITLE
[Export] Commit memoized subjects

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#932]
so that https://github.com/galterlibrary/digital-repository/pull/928 can be merged and released in order to get the memoized list.

**Comment by Meowcenary** [comment]
I'm going to address the review comments on my open PR, merge that, then branch off of master (which will include the open PR), before rebasing off the updated resource types PR. Once that is all done I will deploy to staging (or prod if we prefer) to run the export to build the memoized header file.

**Comment by Meowcenary** [comment]
I think that I've logged all the headers that are failing to look up at this point, but I'm running the export again now that I've worked out some bugs that were preventing it from completing. If there is nothing new to add to my list then I will send it out to the experts and hopefully what I've looked up will help in figuring out how to resolve this.

**Comment by fenekku** [comment]
This is now done whenever a new export is made if there are new entries and/or when memoized subjects are fixed when addressing a bug. Marking it closed.
