### ISSUE TITLE
Export records of interest (or all records)

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#941]
Karen shared the records of interest for the import validation checks. Those are:

doi:10.18131/G3CC7P
doi:10.18131/g3-47z6-xc12
doi:10.18131/g3-ae5n-fz91
doi:10.18131/G3MK7X
doi:10.18131/g3-wqpb-8236
doi:10.18131/g3-wshx-rb04
doi:10.18131/g3-te03-qn58
doi:10.18131/g3-e3kr-ex06
doi:10.18131/g3-1nay-5a37
doi:10.18131/G36K76
doi:10.18131/g3-5qz7-3f18
doi:10.15844/pedneurbriefs-11-10-8
doi:10.18131/G3V30M
doi:10.18131/g3-sx6n-0k83
doi:10.18131/G3P32T
doi:10.18131/G3WB23
doi:10.18131/G34K5T
doi:10.18131/g3-9mhj-4m66
doi:10.18131/g3-58gj-j278
doi:10.18131/G3G599
doi:10.18131/G3GP4K

Of these, the following I already have:

doi:10.18131/G3GP4K,2021_08_26_metadata_sample/generic_file_jw827b648.json
doi:10.18131/G3G599,2021_08_26_metadata_sample/generic_file_j3860692c.json
doi:10.18131/G3V30M,2021_08_26_metadata_sample/generic_file_n009w228g.json
doi:10.18131/G34K5T,2021_08_26_metadata_sample/generic_file_5425k968s.json
doi:10.18131/G3CC7P,2021_08_26_metadata_sample/generic_file_6t053f96k.json

(I also retrieved their files)

It would be nice to have an export containing the others so they can all be validated. If a full export is done, then we should be good. Just making a ticket so we keep track of this.

**Comment by Meowcenary** [comment]
We are closing this ticket since we already have an epic ("Export DH record to InvenioRDM record") in place that captures what this ticket was supposed to achieve.
