### ISSUE TITLE
[Export] Missing files key

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#952]
**Missing files key**
e.g., Couldn't import generic_file_pnb-10-9-70-b.json --> https://digitalhub.northwestern.edu/files/pnb-10-9-70-b
Error 'files'

The exported json is missing the `"record": { "files": ...}` key. This is very widespread among the pediatrics briefs. There is a file associated with that record though in the metadata json. Strange.

**Comment by fenekku** [comment]
**update 2021-10-28 export**: No records with this issue!

 Let's still keep an eye on this until we get full export.

**Comment by Meowcenary** [comment]
@fenekku to follow up on this and decide if it should stay open or not.

**Comment by fenekku** [comment]
Update from 2021-11-03 batch: No records with this issue.

Closing this.
