### ISSUE TITLE
[Export] Remove Rescue Block in Export

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#959]
Undo #956. There was one record that was causing the export to break. The record was https://digitalhub.northwestern.edu/files/nv9352930, and the issue was that creator had a comma at the end that we do not deal with.

**Comment by fenekku** [comment]
Hmmm, I wouldn't remove the rescue block until we have done the full export (all records and done in practice). I don't think there is any drawback in keeping it, right? and it will surely catch future problems.

**Comment by sharpattack** [comment]
There were two concerns why I was thinking of removing:
1. The rescue was too broad. While we did get some error info, it wasn't specific enough, IMO. 
2. I wonder if the way the current logger is set up, I may be adding to memory overload. Although there is only one log file, there is a "new" logger every time we rescue an error. (Yes, we only had one error anyway)

So, we can disagree on the broad range, because I do agree we want to catch future problems. I think it may be better to refactor and remove the Logger piece, and just print out the error, which will be redirected to a debugging file anyway. One less file then.

Just some thoughts, we do not have to act on this until we are desperately trying to fix the slowness of the export.

**Comment by Meowcenary** [comment]
Closing this since the memory issues seem to be resolved after changing to JSONL formatted files AND we're still using it to help debug things. We can remove later with another commit if we want to benchmark, but given how long exports take I don't expect it to make a huge difference.
