### ISSUE TITLE
Export Collection Info

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#963]
Export new key "communities" with collection info a record belongs to in DigitalHub. 

```
{
  "record": {
    ...
  },
  "file": {
    ...
  },
  "extras": {
    ...
  },
  "communities": [
    {
      "id": <id>,
      "url": <url>,
      "title": <title>
    }
  ]
}
```

**Comment by fenekku** [comment]
@sharpattack 

Can a record in DH belong to multiple communities/collections? Will the deeply nested records have all their collections listed hierarchically?

```
"communities": [
  {
    "id": <id top most collection>,
    "url": <url>
    "title": <title>
  },
  ...
  {
    "id": <id bottom most collection>,
    "url": <url>
    "title": <title>
  }
]
```

**Comment by sharpattack** [comment]
@fenekku Yes, a record can belong to multiple collections. We will only export info for the collection(s) it is in, and not any of the collection's parent/child collections, unless the record is also in those.

**Comment by fenekku** [comment]
**Updated structure**

Let's say record A is "located" in these 2 places in DH:  
  Community B > Collection B1 > Collection B1-1
  Community Z > Collection Z1

Then the export would have:

```
"communities": [
  [{"title": "Community B", ...}, {"title": "Collection B1", ...}, {"title": "Collection B1-1", ...}],
  [{"title": "Community Z", ...}, {"title": "Collection Z1", ...}],
]
```
