### ISSUE TITLE
Create List of Collection Owners with Info

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#983]
Check if this info is already available. If not, decide where to extract this info: add it to the metadata, create a one off script to export a list of this info in a CSV file, other? Include info of record owners if the record is in a collection, but they are not a collection owner.

netid, last name, first name, email, anything else?

**Comment by Meowcenary** [comment]
We need to clarify what record owners are. Currently we think that the depositor AND users that have read permissions are considered to be owners.

With that, the code would look something like this:

```
Collection.all.each do |collection|
    collection_owners = collection.depositor + collection.get_users_with_read_permissions # implement some function to collect users that have read permissions
     
    collection_owners.each do |collection_owner|
       User.find_by(net_id: collection_owenr.net_id)
       # do stuff to format as CSV row
     end
     
     # write out CSV
end
```
