### ISSUE TITLE
22-02-2022-dh-export.tar.gz export issues

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#987]
Analysis from the 22-02-2022-dh-export.tar.gz highlighted these issues to be resolved:

# 0
Pages are exported even though they are subsumed by generic files.
    Example: tmp/export/generic_file_td96k250z.json and tmp/export/page_td96k250z.json are the same
    There are 1975 pages and they are all doubles of generic_files.

# 1
Missing publication/creation date: 4
    tmp/export/generic_file_fq977t82f.json
    tmp/export/generic_file_9c67wm919.json
    tmp/export/generic_file_qb98mf520.json
    tmp/export/generic_file_b2773v70j.json
Basically: https://github.com/galterlibrary/digital-repository/issues/953

# 2
Deviant MeSH identifiers: 3
    tmp/export/generic_file_td96k250z.json
    tmp/export/generic_file_xk81jk370.json
    tmp/export/generic_file_kw52j807h.json

Of the form e.g. https://meshb.nlm.nih.gov/mesh/D000038 when they should be https://id.nlm.nih.gov/mesh/D000038
(sounds like a regression)

# 3
Duplicate subject : 150
    Example: tmp/export/generic_file_library-notes-5.json

I thought the reason for those was that some of them were unmapped LCNAF terms
i.e. one of the term comes from DH's keyword field and the other comes from DH's subject name field.
The subject name one should have been translated to its identifier, no? If this whole assumption is
not the case, deduplication should be done. (regression?)

# 4
Empty json files are exported: 1970
    Example: tmp/export/generic_file_f932d9f2-c137-4592-8af8-50447ca57647.json

I suspect those are because they were part of the records we didn't want to export, but I don't know for sure.
Either way, not exporting them at all would be clearer.

# 5
prism_communities is exported in different formats:
    tmp/export/generic_file_library-notes-5.json
    `"prism_communities": ["galter-health-sciences-library-and-learning-center"]`

    tmp/export/generic_file_cea8e826-6479-44f3-8e72-ad646e85c213.json
```
    "prism_communities": [
    [
      {
        "title": "PD language prediction experiment data and analysis scripts",
        "id": "1d4cede9-d8d6-4576-994d-91d36bd15b0b"
      }
    ]
  ]
```

Related to communities.json file having: "galter-health-sciences-library-&-learning-center"? but actually should have (as per export):
"galter-health-sciences-library-and-learning-center".

**Comment by Meowcenary** [comment]
0, 2, and 4 were quick to address and I've made changes for
1 - has a ticket already
3 - I will make a ticket for
5 - I will look into and see if I can fit it in with what I have so far.

**Comment by fenekku** [comment]
Another issue related to 5) I've seen on 1 exported file is duplicate community ids. The cycle protection code should be doublechecked to make sure the community that starts the cycle is not outputted twice.

The file is generic_file_d85443d7-8d81-4bcd-97e8-2cd7bdaf8750.json with:

```json
  "prism_communities": [
    "nucats-grants-repository",
    "nucats-grants-repository"
  ],
```
