### ISSUE TITLE
[Export] Invalid related identifiers url 

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#995]
Some exported files have invalid related identifier urls:

```json
    "related_identifiers": [
        {
          "identifier": "Conducting a Systematic Review: Part 1, Planning the Process - Video 1 (Video) https://digitalhub.northwestern.edu/files/5b109f03-2a29-4c58-bbdb-53fcde2c17e5",
          "relation_type": {
            "id": "isRelatedTo"
          },
          "scheme": "url"
        },
        {
          "identifier": "Conducting a Systematic Review: Part 1, Planning the Process - Video 2 (Video) https://digitalhub.northwestern.edu/files/e9535999-3c97-4cd3-88f4-f3824fd48a67",
          "relation_type": {
            "id": "isRelatedTo"
          },
          "scheme": "url"
        },
        {
          "identifier": "Conducting a Systematic Review: Part 1, Planning the Process - Video 3 (Video) https://digitalhub.northwestern.edu/files/ac71fb3b-ee25-4e9a-89a3-08129b80e904",
          "relation_type": {
            "id": "isRelatedTo"
          },
          "scheme": "url"
        }
```

When the `scheme` is `url`, the `identifier` has to be a valid URL starting with `http`.

The expected `related_identifiers` for the above would be:

```json
    "related_identifiers": [
        {
          "identifier": "<https//doi url of https://digitalhub.northwestern.edu/files/5b109f03-2a29-4c58-bbdb-53fcde2c17e5>",
          "relation_type": {
            "id": "isRelatedTo"
          },
          "scheme": "url"
        },
        {
          "identifier": "<https//doi url of https://digitalhub.northwestern.edu/files/5b109f03-2a29-4c58-bbdb-53fcde2c17e5>",
          "relation_type": {
            "id": "isRelatedTo"
          },
          "scheme": "url"
        },
        {
          "identifier": "<https//doi url of https://digitalhub.northwestern.edu/files/5b109f03-2a29-4c58-bbdb-53fcde2c17e5>",
          "relation_type": {
            "id": "isRelatedTo"
          },
          "scheme": "url"
        }
```

Notice the use of the doi URL in this case as the better practice. We know we may not be able to retire the DH URL right away and will probably have to carry around some redirects, but if we can not add to the deprecated links it would be best.

Here is the potentially non-exhaustive list of exported json with that issue:

    - generic_file_15cbfda3-608d-4f20-bdb5-872260994bf5.json
    - generic_file_1bff6ec0-af92-48dd-a8e2-d17e4ac4f1ec.json
    - generic_file_0897d2f4-ca26-4194-88e5-5482858eb05a.json
    - generic_file_684b998f-54be-4d96-92e4-a9de5af3044a.json
    - generic_file_9816f884-8d76-4108-950a-131f5b9b976d.json
    - generic_file_5b109f03-2a29-4c58-bbdb-53fcde2c17e5.json
    - generic_file_ac71fb3b-ee25-4e9a-89a3-08129b80e904.json

The list is potentially non-exhaustive as other errors during import may have masked this error in other imports.

This may be an export and/or intrinsic DH record metadata issue so I am tagging @gneidhardt too.

**Comment by gneidhardt** [comment]
This one is really strange. For all the Systematic Review videos, the DOIs are not valid - using the https://doi.org/xxx form leads to an Error: DOI not found page. Since that is not working, I kept the DH URLs in the description and removed the descriptive text. This covers:
https://digitalhub.northwestern.edu/files/ac71fb3b-ee25-4e9a-89a3-08129b80e904
https://digitalhub.northwestern.edu/files/e9535999-3c97-4cd3-88f4-f3824fd48a67
https://digitalhub.northwestern.edu/files/684b998f-54be-4d96-92e4-a9de5af3044a
https://digitalhub.northwestern.edu/files/15cbfda3-608d-4f20-bdb5-872260994bf5
https://digitalhub.northwestern.edu/files/5b109f03-2a29-4c58-bbdb-53fcde2c17e5
https://digitalhub.northwestern.edu/files/0897d2f4-ca26-4194-88e5-5482858eb05a

This one is just a URL to a related external website - do we create a DOI for those? https://digitalhub.northwestern.edu/files/1bff6ec0-af92-48dd-a8e2-d17e4ac4f1ec

Lastly this one was just an error and has been fixed:
https://digitalhub.northwestern.edu/files/9816f884-8d76-4108-950a-131f5b9b976d

**Comment by fenekku** [comment]
Ah I see. Because the records are Northwestern Only, the DOI is only reserved i.e. it doesn't resolve nor expose its metadata publicly. Keeping the digitalhub links for now makes the most sense :+1: .

The use of the DOI url should just be for links that do have one (typically our own, but as just seen for certain permissions that link doesn't resolve so can't be used either). For external links, we just keep the external link as is.

**Comment by fenekku** [comment]
@gneidhardt we will need your help once again!

From the 2022-04-12 export/import the following records have invalid related urls :

- generic_file_1bff6ec0-af92-48dd-a8e2-d17e4ac4f1ec.json
    * In https://digitalhub.northwestern.edu/files/1bff6ec0-af92-48dd-a8e2-d17e4ac4f1ec change related url
        - www.thirdcoastcfar.org/ethicsconsultation2017 to https://www.thirdcoastcfar.org/ethicsconsultation2017/
- generic_file_486409bf-ba82-43d7-b2a4-7b94d8914cda.json
    * In https://digitalhub.northwestern.edu/files/486409bf-ba82-43d7-b2a4-7b94d8914cda change related url
        - www.stattag.org to https://sites.northwestern.edu/stattag/
- generic_file_707957642.json
    * In https://digitalhub.northwestern.edu/files/ change
        - hsli.org/midwestmla2013/docs/posters.pdf -> https://hsli.org/midwestmla2013/docs/posters.pdf

**Comment by gneidhardt** [comment]
Done!

**Comment by fenekku** [comment]
Double-checked with latest export. All of these encountered issues are resolved.

**Comment by Meowcenary** [comment]
Well, there's a bit of good
