### ISSUE TITLE
File 357573d1-61cd-45d8-8c31-2924e66841dc has an extra creator without a name

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#996]
The exported file generic_file_357573d1-61cd-45d8-8c31-2924e66841dc.json has an extra creator with name `" "` which is invalid for import.

```
      "creators": [
        {
          "person_or_org": {
            "name": "12th General Hospital",
            "type": "organizational"
          }
        },
        {
          "person_or_org": {
            "name": " ",
            "type": "organizational"
          }
        }
      ],
```

This is most likely a metadata curation task so I am tagging @gneidhardt . (I see the additional creator as removed or filled in with appropriate name)

**Comment by gneidhardt** [comment]
Can you tell me what the title or DOI is for this file? Or let me know if I can see this .json file and I can try to locate it myself if that's easier.

**Comment by fenekku** [comment]
Ah yes, the alphanumeric code is its Digitalhub id, so it can be accessed by appending it to `https://digitalhub.northwestern.edu/files/`. In this case it would be: `https://digitalhub.northwestern.edu/files/357573d1-61cd-45d8-8c31-2924e66841dc`

**Comment by gneidhardt** [comment]
Looks like this issue is fixed (though in case we need more information or if this issue comes up again - there wasn't an empty creator visible. I deleted the only current creator "12th General Hospital" and then added it back and that seemed to fix it).

**Comment by fenekku** [comment]
This is one of the files for which the `metadata` key has been set to null in the export (see https://github.com/galterlibrary/digital-repository/issues/1013). Marking it as blocked until we have a resolution on this from the export.

**Comment by fenekku** [comment]
Resolved as of 2022-04-26 export.
