### ISSUE TITLE
[Export] Invalid funding for some files

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#997]
Some exported files have invalid funding data like:

```json
"funding": [
        {
          "award": {
            "identifier": "",
            "number": "",
            "scheme": "",
            "title": ""
          },
          "funder": {
            "identifier": "",
            "name": "",
            "scheme": "ror"
          }
        }
      ],
```
These empty award-funder should be removed:

```json
"funding": []
```

See https://inveniordm.docs.cern.ch/reference/metadata/#funding-references-0-n for the expected shape / arity of the `funding` field.  

The non-exhausitve list of affected files are:

-    generic_file_b876a078-d5da-4f9f-b8e4-cc1cd75489a5.json
-    generic_file_c423cf8b-8cbb-4407-9b3e-dd30bd86769a.json
-    generic_file_b93105d8-0142-4ddb-baa0-64fea8b981b2.json
-    generic_file_78254bed-92a7-4708-bcff-16383bab9ce3.json
 
It's non-exhaustive because other import errors may have masked those.

This may be a metadata curation issue so I am tagging @gneidhardt as well.

**Comment by fenekku** [comment]
**2022-04-13**

Issue https://github.com/galterlibrary/digital-repository/issues/1013 affects all these records:

- generic_file_b876a078-d5da-4f9f-b8e4-cc1cd75489a5.json 
- generic_file_c423cf8b-8cbb-4407-9b3e-dd30bd86769a.json
- generic_file_b93105d8-0142-4ddb-baa0-64fea8b981b2.json
- generic_file_78254bed-92a7-4708-bcff-16383bab9ce3.json

have metadata `null` so this can't be checked for now.

**Comment by fenekku** [comment]
As of the 2022-04-26 export this issue is still valid. Here are _all_ the records in the export with that problem:

https://digitalhub.northwestern.edu/files/b876a078-d5da-4f9f-b8e4-cc1cd75489a5
https://digitalhub.northwestern.edu/files/c423cf8b-8cbb-4407-9b3e-dd30bd86769a
https://digitalhub.northwestern.edu/files/b93105d8-0142-4ddb-baa0-64fea8b981b2
https://digitalhub.northwestern.edu/files/78254bed-92a7-4708-bcff-16383bab9ce3
https://digitalhub.northwestern.edu/files/45a68a08-9aa6-4e13-8f7e-fd20f9d87010
https://digitalhub.northwestern.edu/files/1bff6ec0-af92-48dd-a8e2-d17e4ac4f1ec
https://digitalhub.northwestern.edu/files/8p58pc98c
https://digitalhub.northwestern.edu/files/0z708w45r
https://digitalhub.northwestern.edu/files/ae10b9d6-f1d1-43bc-a5bc-2b6e024d263b
https://digitalhub.northwestern.edu/files/hx11xf327
https://digitalhub.northwestern.edu/files/d43f1bbc-9099-45fa-83e2-79d1301a0aeb

This happens because those records have funding information but it couldn't be automatically parsed  and formatted at export time into the structure expected by InvenioRDM. Examples of the values found in the above:

- "This report was made possible with help from the Third Coast Center for AIDS Research (CFAR), an NIH funded center (P30 AI117943), including funding from an administrative supplement to that grant." 
- "See PRO Planning Tools Overview"
- "IGH"

**Possible solution**

The list is small and parsing is hard so an automated solution is out. 

An easy solution would be for @gneidhardt to fill the funding field for each of those in a file that she shares with us (csv would be nice :smiley_cat: ). Then I can use that file to enhance the metadata of those records at import time with the appropriate funding information. I already have a means to do this as part of the import for any metadata field.

For the funding field to be valid in Prism (InvenioRDM) the following structure/rules must be met: https://inveniordm.docs.cern.ch/reference/metadata/#funding-references-0-n . In other words, if neither `funder` nor `award` can be filled with their required values, then we can't use the funding field. In that case, I think putting the information in the description on DigitalHub and removing the funding field is the best we can do to preserve what little information we have, while not preventing the import of the record.

 Chime in if any thoughts.

**Comment by gneidhardt** [comment]
I'm coming off a multiple-meetings day, so I might be a bit fuzzy, but wanted to check in on this. If I put together a csv with the following columns would that work?

- file name
- funder-name
- funder-scheme
- funder-identifier
- award-title
- award-number
- award-scheme
- award-identifier

Is there any other information you'd need? Do you need every funder field and/or every award field filled out, or would it be enough to have say just file name and award-title filled out?

**Comment by fenekku** [comment]
The mentioned columns are good.

The funder/award fields just need to follow https://inveniordm.docs.cern.ch/reference/metadata/#funding-references-0-n . That is, if any information about funder is entered in the csv, then at least funder-name is required (not empty). If any information about award is entered, then at least award-title AND award-number are needed.

**Comment by gneidhardt** [comment]
If there is more than one funder or award, are these fields repeatable? And if so should I have multiple sets of columns in the CSV, or separate some other way?

**Comment by fenekku** [comment]
Multiple rows with the same file name but different values for the other columns is fine :+1: .

**Comment by gneidhardt** [comment]
Also this is an incredibly basic question, but as I have not parsed out this metadata before beyond a free-text field, what has generally gone in the award-title? 

- the full name of the grant applied for (ie "EHR Access to Seamless Integration of PROMIS (EASI-PRO) grant")
- the name of the specific grant project "ie "IMPROVING PATIENT REPORTED OUTCOME DATA FOR RESEARCH THROUGH SEAMLESS INTEGRATION OF THE PROMIS TOOLKIT INTO EHR WORKFLOWS") (Note: this is generally what I defaulted to)
- the full name of the awarding organization (ie "National Center for Advancing Translational Sciences (NCATS)")

I'm grabbing most of the information from the files themselves, then looking up the award agency in the ROR database and using that as the scheme/identifier. I do see in the InvenioRDM instructions that OpenAIRE is recommended for awards, but so far I haven't found any of our awards in there (some final research products, but no information about awards/awarding institutions). I have a feeling I might be overthinking this, but I want to make sure I'm not giving you bad data. Note that my heuristic is generally if there is an award number, put metadata in award fields; if no award number then put metadata in funding fields.

NOTE: for (https://digitalhub.northwestern.edu/files/78254bed-92a7-4708-bcff-16383bab9ce3) I removed the funding note from DigitalHub as the file itself says "Support: No financial support, no review funder or sponsor."
[DigitalHubInvalidFundingFiles.csv](https://github.com/galterlibrary/digital-repository/files/8574815/DigitalHubInvalidFundingFiles.csv)

I'm attaching the CSV file as-is, but please let me know if you'd like me to make any corrections.

**Comment by fenekku** [comment]
Looked at this a little bit but will assess in more details tomorrow. Thanks.

**Comment by gneidhardt** [comment]
Here's take two on the csv error files
[DigitalHubInvalidFundingFiles_v2.csv](https://github.com/galterlibrary/digital-repository/files/8584393/DigitalHubInvalidFundingFiles_v2.csv)
